In [1]:
import re
import math
import warnings
warnings.filterwarnings("ignore")
import datetime
import operator
import numpy as np
import pandas as pd
import seaborn as sns
import datetime as dt
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
pd.set_option('display.max_columns', 550)
pd.set_option('display.max_rows', 550)
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

In [3]:
cp = pd.read_csv('C:/Users/zagkoui/OneDrive - Vodafone Group/Documents/FIXED_VISUALIZATION/cable_providers.csv')

In [4]:
cp[cp["CO_code"] == 1197]

,CO_code,kvID,City,County,Longtitude,Latitude,Provider,VDSL50,VDSL100,VDSL200,Connection_TypeC,Pots,Enabled,CO_Cabin,Connections,Length,CO_kv_Dist,Type
17666,1197,125,ΑΘΗΝΑ,Ν. ΑΤΤΙΚΗΣ,23.772028,37.995333,VF,1,1,1,NaN,100,1,1197-125,77.0,90.0,1056,ΠΥΚΝΟ ΑΣΤΙΚΟ
17667,1197,109,ΑΘΗΝΑ,Ν. ΑΤΤΙΚΗΣ,23.770278,37.994333,VF,1,1,1,NaN,100,1,1197-109,68.0,90.0,613.9,ΠΥΚΝΟ ΑΣΤΙΚΟ
17668,1197,373,ΑΘΗΝΑ,Ν. ΑΤΤΙΚΗΣ,23.764028,37.989333,VF,1,1,1,NaN,100,1,1197-373,80.0,90.0,775,ΠΥΚΝΟ ΑΣΤΙΚΟ
17669,1197,273,ΑΘΗΝΑ,Ν. ΑΤΤΙΚΗΣ,23.774167,37.994167,VF,1,1,1,NaN,100,1,1197-273,91.0,90.0,1067,ΠΥΚΝΟ ΑΣΤΙΚΟ
17670,1197,383,ΑΘΗΝΑ,Ν. ΑΤΤΙΚΗΣ,23.762222,37.989389,VF,1,1,1,NaN,100,1,1197-383,148.0,90.0,876.1,ΠΥΚΝΟ ΑΣΤΙΚΟ
17671,1197,121,ΑΘΗΝΑ,Ν. ΑΤΤΙΚΗΣ,23.7715,37.995361,VF,1,1,1,NaN,100,1,1197-121,109.0,90.0,841,ΠΥΚΝΟ ΑΣΤΙΚΟ
17672,1197,467,ΑΘΗΝΑ,Ν. ΑΤΤΙΚΗΣ,23.763611,38.000611,VF,1,1,1,NaN,100,1,1197-467,129.0,90.0,1036,ΠΥΚΝΟ ΑΣΤΙΚΟ
17673,1197,453,ΑΘΗΝΑ,Ν. ΑΤΤΙΚΗΣ,23.760917,37.997694,VF,1,1,1,NaN,100,1,1197-453,129.0,90.0,993.5,ΠΥΚΝΟ ΑΣΤΙΚΟ
17674,1197,463,ΑΘΗΝΑ,Ν. ΑΤΤΙΚΗΣ,23.763861,37.999389,VF,1,1,1,NaN,100,1,1197-463,124.0,90.0,856,ΠΥΚΝΟ ΑΣΤΙΚΟ
17675,1197,269,ΑΘΗΝΑ,Ν. ΑΤΤΙΚΗΣ,23.773833,37.993639,VF,1,1,1,NaN,100,1,1197-269,128.0,90.0,1048,ΠΥΚΝΟ ΑΣΤΙΚΟ
17676,1197,227,ΑΘΗΝΑ,Ν. ΑΤΤΙΚΗΣ,23.766972,37.989722,VF,1,1,1,NaN,100,1,1197-227,160.0,90.0,755.2,ΠΥΚΝΟ ΑΣΤΙΚΟ
17677,1197,235,ΑΘΗΝΑ,Ν. ΑΤΤΙΚΗΣ,23.768389,37.989972,VF,1,1,1,NaN,100,1,1197-235,151.0,90.0,746,ΠΥΚΝΟ ΑΣΤΙΚΟ
17678,1197,249,ΑΘΗΝΑ,Ν. ΑΤΤΙΚΗΣ,23.771222,37.992083,VF,1,1,1,NaN,100,1,1197-249,155.0,90.0,757.1,ΠΥΚΝΟ ΑΣΤΙΚΟ
17679,1197,335,ΑΘΗΝΑ,Ν. ΑΤΤΙΚΗΣ,23.764556,37.990861,VF,1,1,1,NaN,100,1,1197-335,160.0,90.0,651.2,ΠΥΚΝΟ ΑΣΤΙΚΟ
17680,1197,117,ΑΘΗΝΑ,Ν. ΑΤΤΙΚΗΣ,23.768528,37.996111,VF,1,1,1,NaN,100,1,1197-117,166.0,90.0,663,ΠΥΚΝΟ ΑΣΤΙΚΟ
17681,1197,111,ΑΘΗΝΑ,Ν. ΑΤΤΙΚΗΣ,23.769917,37.995833,VF,1,1,1,NaN,100,1,1197-111,152.0,90.0,698,ΠΥΚΝΟ ΑΣΤΙΚΟ
17682,1197,233,ΑΘΗΝΑ,Ν. ΑΤΤΙΚΗΣ,23.768667,37.990444,VF,1,1,1,NaN,100,1,1197-233,160.0,90.0,818,ΠΥΚΝΟ ΑΣΤΙΚΟ
17683,1197,363,ΑΘΗΝΑ,Ν. ΑΤΤΙΚΗΣ,23.760806,37.991972,VF,1,1,1,NaN,100,1,1197-363,167.0,90.0,694,ΠΥΚΝΟ ΑΣΤΙΚΟ
17684,1197,220,ΑΘΗΝΑ,Ν. ΑΤΤΙΚΗΣ,23.768389,37.991306,VF,1,1,1,NaN,100,1,1197-220,173.0,90.0,650.8,ΠΥΚΝΟ ΑΣΤΙΚΟ
17685,1197,339,ΑΘΗΝΑ,Ν. ΑΤΤΙΚΗΣ,23.764278,37.990306,VF,1,1,1,NaN,100,1,1197-339,150.0,90.0,727.2,ΠΥΚΝΟ ΑΣΤΙΚΟ
17686,1197,381,ΑΘΗΝΑ,Ν. ΑΤΤΙΚΗΣ,23.762639,37.989361,VF,1,1,1,NaN,100,1,1197-381,183.0,90.0,897.1,ΠΥΚΝΟ ΑΣΤΙΚΟ
17687,1197,221,ΑΘΗΝΑ,Ν. ΑΤΤΙΚΗΣ,23.766806,37.990528,VF,1,1,1,NaN,100,1,1197-221,168.0,90.0,679.7,ΠΥΚΝΟ ΑΣΤΙΚΟ
17688,1197,263,ΑΘΗΝΑ,Ν. ΑΤΤΙΚΗΣ,23.77325,37.993778,VF,1,1,1,NaN,100,1,1197-263,150.0,90.0,982.5,ΠΥΚΝΟ ΑΣΤΙΚΟ
17689,1197,367,ΑΘΗΝΑ,Ν. ΑΤΤΙΚΗΣ,23.761444,37.990889,VF,1,1,1,NaN,100,1,1197-367,178.0,90.0,596.6,ΠΥΚΝΟ ΑΣΤΙΚΟ
17690,1197,469,ΑΘΗΝΑ,Ν. ΑΤΤΙΚΗΣ,23.765806,37.999222,VF,1,1,1,NaN,100,1,1197-469,146.0,90.0,965.5,ΠΥΚΝΟ ΑΣΤΙΚΟ
17691,1197,477,ΑΘΗΝΑ,Ν. ΑΤΤΙΚΗΣ,23.767083,37.998583,VF,1,1,1,NaN,100,1,1197-477,148.0,90.0,1112,ΠΥΚΝΟ ΑΣΤΙΚΟ
17692,1197,259,ΑΘΗΝΑ,Ν. ΑΤΤΙΚΗΣ,23.772361,37.99275,VF,1,1,1,NaN,100,1,1197-259,184.0,90.0,745.2,ΠΥΚΝΟ ΑΣΤΙΚΟ
17693,1197,365,ΑΘΗΝΑ,Ν. ΑΤΤΙΚΗΣ,23.761222,37.990972,VF,1,1,1,NaN,100,1,1197-365,202.0,90.0,596.6,ΠΥΚΝΟ ΑΣΤΙΚΟ
17694,1197,433,ΑΘΗΝΑ,Ν. ΑΤΤΙΚΗΣ,23.762139,37.995444,VF,1,1,1,NaN,100,1,1197-433,185.0,90.0,659.6,ΠΥΚΝΟ ΑΣΤΙΚΟ
17695,1197,385,ΑΘΗΝΑ,Ν. ΑΤΤΙΚΗΣ,23.760806,37.990472,VF,1,1,1,NaN,100,1,1197-385,179.0,90.0,655.6,ΠΥΚΝΟ ΑΣΤΙΚΟ
17696,1197,113,ΑΘΗΝΑ,Ν. ΑΤΤΙΚΗΣ,23.769944,37.996278,VF,1,1,1,NaN,100,1,1197-113,166.0,90.0,657.5,ΠΥΚΝΟ ΑΣΤΙΚΟ
17697,1197,347,ΑΘΗΝΑ,Ν. ΑΤΤΙΚΗΣ,23.760222,37.993111,VF,1,1,1,NaN,100,1,1197-347,178.0,90.0,699,ΠΥΚΝΟ ΑΣΤΙΚΟ
17698,1197,459,ΑΘΗΝΑ,Ν. ΑΤΤΙΚΗΣ,23.762806,37.999417,VF,1,1,1,NaN,100,1,1197-459,169.0,90.0,843,ΠΥΚΝΟ ΑΣΤΙΚΟ
17699,1197,331,ΑΘΗΝΑ,Ν. ΑΤΤΙΚΗΣ,23.766083,37.991111,VF,1,1,1,NaN,100,1,1197-331,179.0,90.0,664.5,ΠΥΚΝΟ ΑΣΤΙΚΟ
17700,1197,471,ΑΘΗΝΑ,Ν. ΑΤΤΙΚΗΣ,23.761083,38.0,VF,1,1,1,NaN,100,1,1197-471,175.0,90.0,1346,ΠΥΚΝΟ ΑΣΤΙΚΟ
17701,1197,115,ΑΘΗΝΑ,Ν. ΑΤΤΙΚΗΣ,23.77075,37.99575,VF,1,1,1,NaN,100,1,1197-115,177.0,90.0,693.5,ΠΥΚΝΟ ΑΣΤΙΚΟ
17702,1197,439,ΑΘΗΝΑ,Ν. ΑΤΤΙΚΗΣ,23.762944,37.997306,VF,1,1,1,NaN,100,1,1197-439,176.0,90.0,684,ΠΥΚΝΟ ΑΣΤΙΚΟ
17703,1197,440,ΑΘΗΝΑ,Ν. ΑΤΤΙΚΗΣ,23.761139,37.996639,VF,1,1,1,NaN,100,1,1197-440,177.0,90.0,919.4,ΠΥΚΝΟ ΑΣΤΙΚΟ
17704,1197,473,ΑΘΗΝΑ,Ν. ΑΤΤΙΚΗΣ,23.765806,38.000639,VF,1,1,1,NaN,100,1,1197-473,160.0,90.0,1135,ΠΥΚΝΟ ΑΣΤΙΚΟ
17705,1197,355,ΑΘΗΝΑ,Ν. ΑΤΤΙΚΗΣ,23.760722,37.990611,VF,1,1,1,NaN,100,1,1197-355,166.0,90.0,644.4,ΠΥΚΝΟ ΑΣΤΙΚΟ
17706,1197,437,ΑΘΗΝΑ,Ν. ΑΤΤΙΚΗΣ,23.762861,37.996639,VF,1,1,1,NaN,100,1,1197-437,176.0,90.0,813.4,ΠΥΚΝΟ ΑΣΤΙΚΟ
17707,1197,265,ΑΘΗΝΑ,Ν. ΑΤΤΙΚΗΣ,23.772944,37.993083,VF,1,1,1,NaN,100,1,1197-265,171.0,90.0,818.2,ΠΥΚΝΟ ΑΣΤΙΚΟ
17708,1197,245,ΑΘΗΝΑ,Ν. ΑΤΤΙΚΗΣ,23.768972,37.989389,VF,1,1,1,NaN,100,1,1197-245,146.0,90.0,856,ΠΥΚΝΟ ΑΣΤΙΚΟ
17709,1197,443,ΑΘΗΝΑ,Ν. ΑΤΤΙΚΗΣ,23.760722,37.994944,VF,1,1,1,NaN,100,1,1197-443,184.0,90.0,641.6,ΠΥΚΝΟ ΑΣΤΙΚΟ
17710,1197,455,ΑΘΗΝΑ,Ν. ΑΤΤΙΚΗΣ,23.761583,37.998167,VF,1,1,1,NaN,100,1,1197-455,188.0,90.0,833,ΠΥΚΝΟ ΑΣΤΙΚΟ
17711,1197,225,ΑΘΗΝΑ,Ν. ΑΤΤΙΚΗΣ,23.767611,37.990444,VF,1,1,1,NaN,100,1,1197-225,196.0,90.0,641,ΠΥΚΝΟ ΑΣΤΙΚΟ
17712,1197,451,ΑΘΗΝΑ,Ν. ΑΤΤΙΚΗΣ,23.760306,37.996917,VF,1,1,1,NaN,100,1,1197-451,184.0,90.0,1035,ΠΥΚΝΟ ΑΣΤΙΚΟ
17713,1197,389,ΑΘΗΝΑ,Ν. ΑΤΤΙΚΗΣ,23.759111,37.991028,VF,1,1,1,NaN,100,1,1197-389,175.0,90.0,859.1,ΠΥΚΝΟ ΑΣΤΙΚΟ
17714,1197,271,ΑΘΗΝΑ,Ν. ΑΤΤΙΚΗΣ,23.774806,37.992778,VF,1,1,1,NaN,100,1,1197-271,189.0,90.0,1088,ΠΥΚΝΟ ΑΣΤΙΚΟ
17715,1197,387,ΑΘΗΝΑ,Ν. ΑΤΤΙΚΗΣ,23.759472,37.990778,VF,1,1,1,NaN,100,1,1197-387,198.0,90.0,831.6,ΠΥΚΝΟ ΑΣΤΙΚΟ
17716,1197,369,ΑΘΗΝΑ,Ν. ΑΤΤΙΚΗΣ,23.762056,37.990444,VF,1,1,1,NaN,100,1,1197-369,210.0,90.0,692.6,ΠΥΚΝΟ ΑΣΤΙΚΟ
17717,1197,123,ΑΘΗΝΑ,Ν. ΑΤΤΙΚΗΣ,23.77175,37.994889,VF,1,1,1,NaN,100,1,1197-123,97.0,90.0,781.5,ΠΥΚΝΟ ΑΣΤΙΚΟ
17718,1197,465,ΑΘΗΝΑ,Ν. ΑΤΤΙΚΗΣ,23.759889,37.998361,VF,1,1,1,NaN,100,1,1197-465,192.0,90.0,1126,ΠΥΚΝΟ ΑΣΤΙΚΟ
17719,1197,435,ΑΘΗΝΑ,Ν. ΑΤΤΙΚΗΣ,23.761528,37.995694,VF,1,1,1,NaN,100,1,1197-435,200.0,90.0,732.6,ΠΥΚΝΟ ΑΣΤΙΚΟ
17720,1197,341,ΑΘΗΝΑ,Ν. ΑΤΤΙΚΗΣ,23.760556,37.992444,VF,1,1,1,NaN,100,1,1197-341,197.0,90.0,623,ΠΥΚΝΟ ΑΣΤΙΚΟ
17721,1197,119,ΑΘΗΝΑ,Ν. ΑΤΤΙΚΗΣ,23.771222,37.994889,VF,1,1,1,NaN,100,1,1197-119,214.0,90.0,943,ΠΥΚΝΟ ΑΣΤΙΚΟ
17722,1197,445,ΑΘΗΝΑ,Ν. ΑΤΤΙΚΗΣ,23.762333,37.997833,VF,1,1,1,NaN,100,1,1197-445,179.0,90.0,725.5,ΠΥΚΝΟ ΑΣΤΙΚΟ
17723,1197,255,ΑΘΗΝΑ,Ν. ΑΤΤΙΚΗΣ,23.772278,37.991722,VF,1,1,1,NaN,100,1,1197-255,162.0,90.0,764.2,ΠΥΚΝΟ ΑΣΤΙΚΟ
17724,1197,329,ΑΘΗΝΑ,Ν. ΑΤΤΙΚΗΣ,23.763778,37.991028,VF,1,1,1,NaN,100,1,1197-329,198.0,90.0,603.5,ΠΥΚΝΟ ΑΣΤΙΚΟ
17725,1197,357,ΑΘΗΝΑ,Ν. ΑΤΤΙΚΗΣ,23.759667,37.992028,VF,1,1,1,NaN,100,1,1197-357,206.0,90.0,727,ΠΥΚΝΟ ΑΣΤΙΚΟ
17726,1197,127,ΑΘΗΝΑ,Ν. ΑΤΤΙΚΗΣ,23.772528,37.994361,VF,1,1,1,NaN,100,1,1197-127,217.0,90.0,1083,ΠΥΚΝΟ ΑΣΤΙΚΟ
17727,1197,479,ΑΘΗΝΑ,Ν. ΑΤΤΙΚΗΣ,23.761861,38.001861,VF,1,1,1,NaN,100,1,1197-479,193.0,90.0,1258,ΠΥΚΝΟ ΑΣΤΙΚΟ
17728,1197,251,ΑΘΗΝΑ,Ν. ΑΤΤΙΚΗΣ,23.771472,37.992583,VF,1,1,1,NaN,100,1,1197-251,197.0,90.0,630.2,ΠΥΚΝΟ ΑΣΤΙΚΟ
17729,1197,447,ΑΘΗΝΑ,Ν. ΑΤΤΙΚΗΣ,23.759778,37.995056,VF,1,1,1,NaN,100,1,1197-447,210.0,90.0,763.5,ΠΥΚΝΟ ΑΣΤΙΚΟ
17730,1197,371,ΑΘΗΝΑ,Ν. ΑΤΤΙΚΗΣ,23.762861,37.99,VF,1,1,1,NaN,100,1,1197-371,208.0,90.0,774.6,ΠΥΚΝΟ ΑΣΤΙΚΟ
17731,1197,475,ΑΘΗΝΑ,Ν. ΑΤΤΙΚΗΣ,23.761083,38.000917,VF,1,1,1,NaN,100,1,1197-475,201.0,90.0,1123,ΠΥΚΝΟ ΑΣΤΙΚΟ
17732,1197,353,ΑΘΗΝΑ,Ν. ΑΤΤΙΚΗΣ,23.763306,37.990528,VF,1,1,1,NaN,100,1,1197-353,216.0,90.0,880.1,ΠΥΚΝΟ ΑΣΤΙΚΟ
17733,1197,267,ΑΘΗΝΑ,Ν. ΑΤΤΙΚΗΣ,23.772944,37.991917,VF,1,1,1,NaN,100,1,1197-267,196.0,90.0,829.7,ΠΥΚΝΟ ΑΣΤΙΚΟ
17734,1197,247,ΑΘΗΝΑ,Ν. ΑΤΤΙΚΗΣ,23.771417,37.993611,VF,1,1,1,NaN,100,1,1197-247,218.0,90.0,668.8,ΠΥΚΝΟ ΑΣΤΙΚΟ
17735,1197,481,ΑΘΗΝΑ,Ν. ΑΤΤΙΚΗΣ,23.768417,37.9985,VF,1,1,1,NaN,100,1,1197-481,90.0,90.0,1243,ΠΥΚΝΟ ΑΣΤΙΚΟ
17736,1197,483,ΑΘΗΝΑ,Ν. ΑΤΤΙΚΗΣ,23.763556,38.002667,VF,1,1,1,NaN,100,1,1197-483,135.0,90.0,1458,ΠΥΚΝΟ ΑΣΤΙΚΟ
17737,1197,485,ΑΘΗΝΑ,Ν. ΑΤΤΙΚΗΣ,23.765917,37.998472,VF,1,1,1,NaN,100,1,1197-485,101.0,90.0,965,ΠΥΚΝΟ ΑΣΤΙΚΟ

### 1

In [5]:
greek_co_code_coords = pd.read_excel('C:/Users/zagkoui/OneDrive - Vodafone Group/Documents/FIXED_VISUALIZATION/LE_colocation_with_coordinates_20201217..xlsx')
greek_co_code_coords = greek_co_code_coords[["Κωδικός Α/Κ WCRM LLU", "longitude", "latitude", "Νομός Α/Κ"]]

greek_co_code_coords_new = pd.read_excel('C:/Users/zagkoui/OneDrive - Vodafone Group/Documents/FIXED_VISUALIZATION/CO_CODE_COORDINATES.xlsx')
greek_co_code_coords_new = greek_co_code_coords_new[["WCRM", "LONGITUDE", "LATITUDE", "LOCATION"]]

In [6]:
# append two files

In [7]:
greek_co_code_coords["Κωδικός Α/Κ WCRM LLU"].nunique()

945

In [8]:
greek_co_code_coords

     Κωδικός Α/Κ WCRM LLU  longitude   latitude         Νομός Α/Κ
0                       7  22.409432  37.454841          ΑΡΚΑΔΙΑΣ
1                      16  22.853874  37.244403          ΑΡΚΑΔΙΑΣ
2                      23  22.438419  37.151092          ΛΑΚΩΝΙΑΣ
3                      27  22.452459  36.959996          ΛΑΚΩΝΙΑΣ
4                      29  22.565160  36.760664          ΛΑΚΩΝΙΑΣ
..                    ...        ...        ...               ...
940                  2080  20.966867  39.142507             ΑΡΤΑΣ
941                  2082  24.933898  37.436261          ΚΥΚΛΑΔΩΝ
942                  2083  22.521566  40.756624            ΠΕΛΛΗΣ
943                  2087  28.211207  36.380284       ΔΩΔΕΚΑΝΗΣΟΥ
944                  2091  21.485059  38.608638  ΑΙΤΩΛΟΑΚΑΡΝΑΝΙΑΣ

[945 rows x 4 columns]

In [9]:
greek_co_code_coords_new

     WCRM  LONGITUDE   LATITUDE            LOCATION
0    1731  22.084014  40.783467    ΡΙΖΑΡΙ - ΕΔΕΣΣΑΣ
1    1694  22.246540  40.551730             ΗΜΑΘΙΑΣ
2    1353  22.861240  40.465501           ΜΗΧΑΝΙΩΝΑ
3    1354  22.987120  40.497300         ΝΕΟΥ ΡΥΣΙΟΥ
4    1356  23.837111  38.048617            ΜΕΛΙΣΣΙΑ
..    ...        ...        ...                 ...
625  1695  22.317786  40.547088              ΒΕΡΟΙΑ
626  1696  21.790707  40.331734    ΚΟΙΛΩΝ - ΚΟΖΑΝΗΣ
627  1697  23.638006  38.307992  ΟΙΝΟΦΥΤΩΝ ΒΟΙΩΤΙΑΣ
628  1285  22.126028  38.909017          ΣΠΕΡΧΕΙΑΔΑ
629  1288  22.286944  39.737778            ΤΥΡΝΑΒΟΣ

[630 rows x 4 columns]

In [10]:
greek_co_code_coords = greek_co_code_coords.rename({"Κωδικός Α/Κ WCRM LLU" : "WCRM"}, axis=1)
greek_co_code_coords_new = greek_co_code_coords_new.rename({"LONGITUDE" : "longitude", "LATITUDE" : "latitude", "LOCATION": "Νομός Α/Κ"}, axis=1)

In [11]:
greek_co_code_coords_new["WCRM"].nunique()

630

In [12]:
# chk= greek_co_code_coords.merge(greek_co_code_coords_new, on='WCRM')
# chk.shape

In [13]:
co_coords_tmp = greek_co_code_coords.append(greek_co_code_coords_new)
co_coords_tmp.shape

(1575, 4)

In [14]:
co_coords_tmp[co_coords_tmp.duplicated("WCRM", keep=False)].sort_values("WCRM")
co_coords_final = co_coords_tmp.drop_duplicates("WCRM")

     WCRM  longitude   latitude                 Νομός Α/Κ
7      47  22.111926  37.034498                 ΜΕΣΣΗΝΙΑΣ
369    47  22.112298  37.034662                 ΚΑΛΑΜΑΤΑΣ
10     59  21.929222  36.957189                 ΜΕΣΣΗΝΙΑΣ
620    59  21.929486  36.957319                 ΜΕΣΣΗΝΙΑΣ
11     62  21.695455  36.912130                 ΜΕΣΣΗΝΙΑΣ
..    ...        ...        ...                       ...
607  2082  24.933708  37.436525                     ΣΥΡΟΥ
942  2083  22.521566  40.756624                    ΠΕΛΛΗΣ
608  2083  22.521381  40.756616  ΠΑΛΙΑ ΠΕΛΛΑ - ΓΙΑΝΝΙΤΣΩΝ
544  2091  21.484931  38.608594                 ΠΑΡΑΒΟΛΑΣ
944  2091  21.485059  38.608638          ΑΙΤΩΛΟΑΚΑΡΝΑΝΙΑΣ

[1208 rows x 4 columns]

In [15]:
co_coords_final.shape

(971, 4)

In [16]:
co_coords_final

     WCRM  longitude   latitude    Νομός Α/Κ
0       7  22.409432  37.454841     ΑΡΚΑΔΙΑΣ
1      16  22.853874  37.244403     ΑΡΚΑΔΙΑΣ
2      23  22.438419  37.151092     ΛΑΚΩΝΙΑΣ
3      27  22.452459  36.959996     ΛΑΚΩΝΙΑΣ
4      29  22.565160  36.760664     ΛΑΚΩΝΙΑΣ
..    ...        ...        ...          ...
531  9999  23.872140  37.764070            -
545  9001  23.586120  37.959690      ΠΕΙΡΑΙΑ
546  9002  23.759340  37.871820     ΓΛΥΦΑΔΑΣ
547  9003  23.784176  38.009540     ΧΑΛΑΝΔΡΙ
548  9004  23.769520  37.996840  ΑΜΠΕΛΟΚΗΠΟΙ

[971 rows x 4 columns]

### 2

In [17]:
vf_product = pd.read_excel('C:/Users/zagkoui/OneDrive - Vodafone Group/Documents/FIXED_VISUALIZATION/VF_performance_per_area.xlsx', sheet_name='summary',skiprows=1)

In [18]:
vf_product["CO code"].nunique()

2120

In [19]:
# check if there are NaN values
vf_product.isnull().values.any()
# 1. COUNT how many NaN values we have per each column
for entry in list(vf_product.columns.values):
    if vf_product[entry].isnull().sum() > 0:
        print(entry, ": ", vf_product[entry].isnull().sum())
        # I have to check the proportion (null / total input)
        print("The proportion of null values is: ", ((vf_product[entry].isnull().sum() / len(vf_product[entry])) * 100, "%"))

True

VF own AK :  2095
The proportion of null values is:  (98.82075471698113, '%')
submitted 12m :  1239
The proportion of null values is:  (58.44339622641509, '%')
created 12m :  1221
The proportion of null values is:  (57.59433962264151, '%')
submitted 6m :  1239
The proportion of null values is:  (58.44339622641509, '%')
created 6m :  1221
The proportion of null values is:  (57.59433962264151, '%')
VF base (retail services) :  1172
The proportion of null values is:  (55.283018867924525, '%')
Gross 12m :  1281
The proportion of null values is:  (60.424528301886795, '%')
Gross 6m :  1281
The proportion of null values is:  (60.424528301886795, '%')
Gross 12m / ttl lines :  1281
The proportion of null values is:  (60.424528301886795, '%')
Gross 12m / VF Base :  1286
The proportion of null values is:  (60.66037735849057, '%')
Gross 6m / ttl lines :  1281
The proportion of null values is:  (60.424528301886795, '%')
Gross 6m / VF Base :  1286
The proportion of null values is:  (60.66037735849057, '%')
VF MS :  1172
The proportion of null values is:  (55.283018867924525, '%')

### 3

In [20]:
#network_kvid_aggs = pd.read_csv('C:/Users/zagkoui/OneDrive - Vodafone Group/Documents/FIXED_VISUALIZATION/network_co_code_kv_aggs_new.csv')
network_kvid_aggs = pd.read_csv('C:/Users/zagkoui/OneDrive - Vodafone Group/Documents/FIXED_VISUALIZATION/irida_fixed_visualization_co_code_kv_aggs (4).csv')

In [21]:
# check if there are NaN values
network_kvid_aggs.isnull().values.any()
# 1. COUNT how many NaN values we have per each column
for entry in list(network_kvid_aggs.columns.values):
    if network_kvid_aggs[entry].isnull().sum() > 0:
        print(entry, ": ", network_kvid_aggs[entry].isnull().sum())
        # I have to check the proportion (null / total input)
        print("The proportion of null values is: ", ((network_kvid_aggs[entry].isnull().sum() / len(network_kvid_aggs[entry])) * 100, "%"))

True

Longtitude :  18177
The proportion of null values is:  (23.806530195277197, '%')
Latitude :  18177
The proportion of null values is:  (23.806530195277197, '%')

In [22]:
network_kvid_aggs["CO_code"].nunique()
network_kvid_aggs["kvID"].nunique()

841

1085

In [23]:
#test = pd.read_csv('C:/Users/zagkoui/OneDrive - Vodafone Group/Documents/FIXED_VISUALIZATION/970c9267-5b4e-424b-9092-91bc919d4c8b (1).csv')

In [24]:
#test

In [25]:
greek_co_code_coords.head()

   WCRM  longitude   latitude Νομός Α/Κ
0     7  22.409432  37.454841  ΑΡΚΑΔΙΑΣ
1    16  22.853874  37.244403  ΑΡΚΑΔΙΑΣ
2    23  22.438419  37.151092  ΛΑΚΩΝΙΑΣ
3    27  22.452459  36.959996  ΛΑΚΩΝΙΑΣ
4    29  22.565160  36.760664  ΛΑΚΩΝΙΑΣ

In [26]:
greek_co_code_coords.shape

(945, 4)

In [27]:
vf_product.head()

,CO code,CO Name,CO prefecture,OKSY C,VF own AK,Total lines,Total lines only retail services,NGA availability,submitted 12m,created 12m,submitted 6m,created 6m,VF base (retail services),Gross 12m,Gross 6m,Gross 12m / ttl lines,Gross 12m / VF Base,Gross 6m / ttl lines,Gross 6m / VF Base,VF MS
0,729,Κ.ΑΣΙΤΕΣ,ΗΡΑΚΛΕΙΟΥ,ACTIVE,NaN,427,375.76,0.000000,4.0,4.0,1.0,0.0,211.0,1.0,0.0,0.002661,0.004739,0.000000,0.000000,0.561529
1,722,ΚΑΣΤΕΛΛΙ,ΗΡΑΚΛΕΙΟΥ,ACTIVE,NaN,1017,894.96,0.050147,4.0,11.0,1.0,2.0,334.0,2.0,0.0,0.002235,0.005988,0.000000,0.000000,0.373201
2,1713,ΑΓΙΑ ΤΡΙΑΔΑ,ΗΜΑΘΙΑΣ,Inactive,NaN,325,286.00,0.000000,1.0,1.0,0.0,0.0,164.0,1.0,0.0,0.003497,0.006098,0.000000,0.000000,0.573427
3,1952,ΣΤΑΥΡΟΥ,ΛΑΡΙΣΑΣ,ACTIVE,NaN,346,304.48,0.000000,1.0,2.0,0.0,0.0,81.0,1.0,0.0,0.003284,0.012346,0.000000,0.000000,0.266027
4,1528,ΤΑΜΠΟΥΡΙΑ,ΙΩΑΝΝΙΝΩΝ,Inactive,NaN,364,320.32,0.000000,2.0,4.0,2.0,3.0,81.0,1.0,1.0,0.003122,0.012346,0.003122,0.012346,0.252872

In [28]:
vf_product =vf_product[["CO code", "OKSY C", "NGA availability", "VF base (retail services)", "VF MS", "submitted 12m", "created 12m", "submitted 6m", "created 6m"]]

In [29]:
vf_product.shape

(2120, 9)

In [30]:
network_kvid_aggs.head()

,CO_code,kvID,DSL,kvID_mean_Actual_Speed,kvID_mean_disconnections,kvID_num_of_connections,Longtitude,Latitude
0,0,0,100,108040.572797,1.333333,3,NaN,NaN
1,0,0,50,46794.973602,6.103448,29,NaN,NaN
2,0,0,ADSL,8665.717358,17.500000,4,NaN,NaN
3,0,101,50,26841.016129,13.500000,4,NaN,NaN
4,0,101,ADSL,14567.000000,0.000000,1,NaN,NaN

In [31]:
network_kvid_aggs["kvID_mean_Actual_Speed"] = network_kvid_aggs["kvID_mean_Actual_Speed"] / 1000
network_kvid_aggs["kvID_mean_Actual_Speed"] = network_kvid_aggs["kvID_mean_Actual_Speed"].round(2)
network_kvid_aggs["kvID_mean_disconnections"] = network_kvid_aggs["kvID_mean_disconnections"].round(1)

In [32]:
network_kvid_aggs.shape

(76353, 8)

In [33]:
network_kvid_aggs

,CO_code,kvID,DSL,kvID_mean_Actual_Speed,kvID_mean_disconnections,kvID_num_of_connections,Longtitude,Latitude
0,0,0,100,108.04,1.3,3,NaN,NaN
1,0,0,50,46.79,6.1,29,NaN,NaN
2,0,0,ADSL,8.67,17.5,4,NaN,NaN
3,0,101,50,26.84,13.5,4,NaN,NaN
4,0,101,ADSL,14.57,0.0,1,NaN,NaN
...,...,...,...,...,...,...,...,...
76348,995,405,ADSL,17.91,2.0,2,23.705083,40.717083
76349,995,407,50,54.35,32.2,4,23.697417,40.710500
76350,996,113,50,12.61,3.0,1,23.702444,40.664417
76351,996,403,100,107.58,7.0,1,23.691056,40.666583
76352,9996,0,ADSL,21.65,223.0,1,NaN,NaN

In [34]:
network_kvid_aggs["CO_code"].nunique()

841

In [35]:
network_kvid_aggs.dtypes

CO_code                       int64
kvID                          int64
DSL                          object
kvID_mean_Actual_Speed      float64
kvID_mean_disconnections    float64
kvID_num_of_connections       int64
Longtitude                  float64
Latitude                    float64
dtype: object

# 1st layer

### aggregate network info for CO_code

In [36]:
kvid_num = network_kvid_aggs.groupby("CO_code")["kvID"].nunique().reset_index().rename(columns={"kvID":"kvID_num"})
#kvid_num = network_kvid_aggs.groupby(["CO_code"]).agg({'kvID':'count'}).rename(columns={"kvID":"CO_code_kvID_num"})

In [37]:
kvid_num.head(10)

   CO_code  kvID_num
0        0       213
1       10         3
2       14         1
3       16         2
4       24         1
5       27         1
6       45         2
7       47       196
8       56         1
9       59        10

In [38]:
kvid_num[kvid_num["CO_code"]== 477]

     CO_code  kvID_num
199      477       203

In [39]:
CO_code_network_info=network_kvid_aggs.groupby(["CO_code", "DSL"]).agg({'kvID_mean_Actual_Speed':'mean', 'kvID_mean_disconnections':'mean','kvID_num_of_connections':'sum'}).rename(columns= {'kvID_mean_Actual_Speed':'mean_Actual_Speed', 'kvID_mean_disconnections':'mean_disconnections', 'kvID_num_of_connections':'num_of_connections'})

In [40]:
CO_code_network_info["mean_Actual_Speed"] = CO_code_network_info["mean_Actual_Speed"].round(2)
CO_code_network_info["mean_disconnections"] = CO_code_network_info["mean_disconnections"].round(1)

In [41]:
CO_code_network_info.head(20)

              mean_Actual_Speed  mean_disconnections  num_of_connections
CO_code DSL
0       100               82.59                 14.7                  73
        200              212.03                 38.0                   1
        50                44.15                 25.6                 211
        ADSL              12.56                 22.7                  93
10      100               79.26                  7.0                   2
        50                54.88                  6.0                   1
14      50                55.00                  7.0                   1
16      100               18.54                  7.0                   1
        50                54.70                 14.0                   1
24      50                49.73                  2.0                   1
27      100               39.29                171.0                   1
        50                49.25                316.5                   2
45      100              107.77                  5.0                   1
        50                48.51                114.5                   3
47      100               90.75                 16.0                1141
        200              133.71                 77.0                  15
        30                27.13                 26.7                 315
        50                51.45                  9.6                1562
        ADSL              11.46                 31.2                1641
56      50                27.78                 18.0                   1

In [42]:
CO_code_network_info = CO_code_network_info.reset_index("DSL")

In [43]:
CO_code_network_info.head(20)

          DSL  mean_Actual_Speed  mean_disconnections  num_of_connections
CO_code
0         100              82.59                 14.7                  73
0         200             212.03                 38.0                   1
0          50              44.15                 25.6                 211
0        ADSL              12.56                 22.7                  93
10        100              79.26                  7.0                   2
10         50              54.88                  6.0                   1
14         50              55.00                  7.0                   1
16        100              18.54                  7.0                   1
16         50              54.70                 14.0                   1
24         50              49.73                  2.0                   1
27        100              39.29                171.0                   1
27         50              49.25                316.5                   2
45        100             107.77                  5.0                   1
45         50              48.51                114.5                   3
47        100              90.75                 16.0                1141
47        200             133.71                 77.0                  15
47         30              27.13                 26.7                 315
47         50              51.45                  9.6                1562
47       ADSL              11.46                 31.2                1641
56         50              27.78                 18.0                   1

In [44]:
CO_code_network_info = CO_code_network_info.pivot(columns='DSL')

In [45]:
CO_code_network_info

        mean_Actual_Speed                              mean_disconnections  \
DSL                   100     200     30     50   ADSL                 100
CO_code
0                   82.59  212.03    NaN  44.15  12.56                14.7
10                  79.26     NaN    NaN  54.88    NaN                 7.0
14                    NaN     NaN    NaN  55.00    NaN                 NaN
16                  18.54     NaN    NaN  54.70    NaN                 7.0
24                    NaN     NaN    NaN  49.73    NaN                 NaN
...                   ...     ...    ...    ...    ...                 ...
2269                56.06     NaN    NaN  50.19    NaN                39.5
9003                  NaN     NaN  30.72    NaN    NaN                 NaN
9004                  NaN     NaN    NaN  56.32    NaN                 NaN
9005                  NaN     NaN  33.77    NaN    NaN                 NaN
9996                  NaN     NaN    NaN    NaN  21.65                 NaN

                                num_of_connections
DSL       200   30    50   ADSL                100  200   30     50  ADSL
CO_code
0        38.0  NaN  25.6   22.7               73.0  1.0  NaN  211.0  93.0
10        NaN  NaN   6.0    NaN                2.0  NaN  NaN    1.0   NaN
14        NaN  NaN   7.0    NaN                NaN  NaN  NaN    1.0   NaN
16        NaN  NaN  14.0    NaN                1.0  NaN  NaN    1.0   NaN
24        NaN  NaN   2.0    NaN                NaN  NaN  NaN    1.0   NaN
...       ...  ...   ...    ...                ...  ...  ...    ...   ...
2269      NaN  NaN  46.0    NaN                2.0  NaN  NaN    2.0   NaN
9003      NaN  1.0   NaN    NaN                NaN  NaN  1.0    NaN   NaN
9004      NaN  NaN   0.3    NaN                NaN  NaN  NaN    6.0   NaN
9005      NaN  3.0   NaN    NaN                NaN  NaN  1.0    NaN   NaN
9996      NaN  NaN   NaN  223.0                NaN  NaN  NaN    NaN   1.0

[841 rows x 15 columns]

In [46]:
CO_code_network_info.columns = ["_".join((j,k)) for j,k in CO_code_network_info.columns]
CO_code_network_info.reset_index()

,CO_code,mean_Actual_Speed_100,mean_Actual_Speed_200,mean_Actual_Speed_30,mean_Actual_Speed_50,mean_Actual_Speed_ADSL,mean_disconnections_100,mean_disconnections_200,mean_disconnections_30,mean_disconnections_50,mean_disconnections_ADSL,num_of_connections_100,num_of_connections_200,num_of_connections_30,num_of_connections_50,num_of_connections_ADSL
0,0,82.59,212.03,NaN,44.15,12.56,14.7,38.0,NaN,25.6,22.7,73.0,1.0,NaN,211.0,93.0
1,10,79.26,NaN,NaN,54.88,NaN,7.0,NaN,NaN,6.0,NaN,2.0,NaN,NaN,1.0,NaN
2,14,NaN,NaN,NaN,55.00,NaN,NaN,NaN,NaN,7.0,NaN,NaN,NaN,NaN,1.0,NaN
3,16,18.54,NaN,NaN,54.70,NaN,7.0,NaN,NaN,14.0,NaN,1.0,NaN,NaN,1.0,NaN
4,24,NaN,NaN,NaN,49.73,NaN,NaN,NaN,NaN,2.0,NaN,NaN,NaN,NaN,1.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
836,2269,56.06,NaN,NaN,50.19,NaN,39.5,NaN,NaN,46.0,NaN,2.0,NaN,NaN,2.0,NaN
837,9003,NaN,NaN,30.72,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,1.0,NaN,NaN
838,9004,NaN,NaN,NaN,56.32,NaN,NaN,NaN,NaN,0.3,NaN,NaN,NaN,NaN,6.0,NaN
839,9005,NaN,NaN,33.77,NaN,NaN,NaN,NaN,3.0,NaN,NaN,NaN,NaN,1.0,NaN,NaN
840,9996,NaN,NaN,NaN,NaN,21.65,NaN,NaN,NaN,NaN,223.0,NaN,NaN,NaN,NaN,1.0

In [47]:
CO_code_network_info = CO_code_network_info.merge(kvid_num, on="CO_code")

In [48]:
CO_code_network_info = CO_code_network_info.reset_index()

In [49]:
CO_code_network_info

,index,CO_code,mean_Actual_Speed_100,mean_Actual_Speed_200,mean_Actual_Speed_30,mean_Actual_Speed_50,mean_Actual_Speed_ADSL,mean_disconnections_100,mean_disconnections_200,mean_disconnections_30,mean_disconnections_50,mean_disconnections_ADSL,num_of_connections_100,num_of_connections_200,num_of_connections_30,num_of_connections_50,num_of_connections_ADSL,kvID_num
0,0,0,82.59,212.03,NaN,44.15,12.56,14.7,38.0,NaN,25.6,22.7,73.0,1.0,NaN,211.0,93.0,213
1,1,10,79.26,NaN,NaN,54.88,NaN,7.0,NaN,NaN,6.0,NaN,2.0,NaN,NaN,1.0,NaN,3
2,2,14,NaN,NaN,NaN,55.00,NaN,NaN,NaN,NaN,7.0,NaN,NaN,NaN,NaN,1.0,NaN,1
3,3,16,18.54,NaN,NaN,54.70,NaN,7.0,NaN,NaN,14.0,NaN,1.0,NaN,NaN,1.0,NaN,2
4,4,24,NaN,NaN,NaN,49.73,NaN,NaN,NaN,NaN,2.0,NaN,NaN,NaN,NaN,1.0,NaN,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
836,836,2269,56.06,NaN,NaN,50.19,NaN,39.5,NaN,NaN,46.0,NaN,2.0,NaN,NaN,2.0,NaN,1
837,837,9003,NaN,NaN,30.72,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,1.0,NaN,NaN,1
838,838,9004,NaN,NaN,NaN,56.32,NaN,NaN,NaN,NaN,0.3,NaN,NaN,NaN,NaN,6.0,NaN,1
839,839,9005,NaN,NaN,33.77,NaN,NaN,NaN,NaN,3.0,NaN,NaN,NaN,NaN,1.0,NaN,NaN,1
840,840,9996,NaN,NaN,NaN,NaN,21.65,NaN,NaN,NaN,NaN,223.0,NaN,NaN,NaN,NaN,1.0,1

In [50]:
CO_code_network_info["num_of_connections_ADSL"] = CO_code_network_info["num_of_connections_ADSL"].fillna(0)
CO_code_network_info["num_of_connections_30"] = CO_code_network_info["num_of_connections_30"].fillna(0)
CO_code_network_info["num_of_connections_50"] = CO_code_network_info["num_of_connections_50"].fillna(0)
CO_code_network_info["num_of_connections_100"] = CO_code_network_info["num_of_connections_100"].fillna(0)
CO_code_network_info["num_of_connections_200"] = CO_code_network_info["num_of_connections_200"].fillna(0)

In [51]:
CO_code_network_info["ttl_num_of_connections"] =CO_code_network_info["num_of_connections_ADSL"] + CO_code_network_info["num_of_connections_30"] + CO_code_network_info["num_of_connections_50"] + CO_code_network_info["num_of_connections_100"]+ CO_code_network_info["num_of_connections_200"]

In [52]:
CO_code_network_info

,index,CO_code,mean_Actual_Speed_100,mean_Actual_Speed_200,mean_Actual_Speed_30,mean_Actual_Speed_50,mean_Actual_Speed_ADSL,mean_disconnections_100,mean_disconnections_200,mean_disconnections_30,mean_disconnections_50,mean_disconnections_ADSL,num_of_connections_100,num_of_connections_200,num_of_connections_30,num_of_connections_50,num_of_connections_ADSL,kvID_num,ttl_num_of_connections
0,0,0,82.59,212.03,NaN,44.15,12.56,14.7,38.0,NaN,25.6,22.7,73.0,1.0,0.0,211.0,93.0,213,378.0
1,1,10,79.26,NaN,NaN,54.88,NaN,7.0,NaN,NaN,6.0,NaN,2.0,0.0,0.0,1.0,0.0,3,3.0
2,2,14,NaN,NaN,NaN,55.00,NaN,NaN,NaN,NaN,7.0,NaN,0.0,0.0,0.0,1.0,0.0,1,1.0
3,3,16,18.54,NaN,NaN,54.70,NaN,7.0,NaN,NaN,14.0,NaN,1.0,0.0,0.0,1.0,0.0,2,2.0
4,4,24,NaN,NaN,NaN,49.73,NaN,NaN,NaN,NaN,2.0,NaN,0.0,0.0,0.0,1.0,0.0,1,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
836,836,2269,56.06,NaN,NaN,50.19,NaN,39.5,NaN,NaN,46.0,NaN,2.0,0.0,0.0,2.0,0.0,1,4.0
837,837,9003,NaN,NaN,30.72,NaN,NaN,NaN,NaN,1.0,NaN,NaN,0.0,0.0,1.0,0.0,0.0,1,1.0
838,838,9004,NaN,NaN,NaN,56.32,NaN,NaN,NaN,NaN,0.3,NaN,0.0,0.0,0.0,6.0,0.0,1,6.0
839,839,9005,NaN,NaN,33.77,NaN,NaN,NaN,NaN,3.0,NaN,NaN,0.0,0.0,1.0,0.0,0.0,1,1.0
840,840,9996,NaN,NaN,NaN,NaN,21.65,NaN,NaN,NaN,NaN,223.0,0.0,0.0,0.0,0.0,1.0,1,1.0

In [53]:
CO_code_network_info.dtypes

index                         int64
CO_code                       int64
mean_Actual_Speed_100       float64
mean_Actual_Speed_200       float64
mean_Actual_Speed_30        float64
mean_Actual_Speed_50        float64
mean_Actual_Speed_ADSL      float64
mean_disconnections_100     float64
mean_disconnections_200     float64
mean_disconnections_30      float64
mean_disconnections_50      float64
mean_disconnections_ADSL    float64
num_of_connections_100      float64
num_of_connections_200      float64
num_of_connections_30       float64
num_of_connections_50       float64
num_of_connections_ADSL     float64
kvID_num                      int64
ttl_num_of_connections      float64
dtype: object

In [54]:
CO_code_network_info.shape

(841, 19)

In [55]:
CO_code_network_info["CO_code"].nunique()

841

# !!! +++++++

In [56]:
non_common_rows2 = co_coords_final.merge(CO_code_network_info, left_on="WCRM", right_on='CO_code', how='left', indicator=True)
non_common_rows2 = non_common_rows2[non_common_rows2['_merge'] == 'left_only']

# Drop the _merge column
non_common_rows2 = non_common_rows2.drop('_merge', axis=1)

In [57]:
non_common_rows2.shape

(276, 23)

In [58]:
non_common_rows2

,WCRM,longitude,latitude,Νομός Α/Κ,index,CO_code,mean_Actual_Speed_100,mean_Actual_Speed_200,mean_Actual_Speed_30,mean_Actual_Speed_50,mean_Actual_Speed_ADSL,mean_disconnections_100,mean_disconnections_200,mean_disconnections_30,mean_disconnections_50,mean_disconnections_ADSL,num_of_connections_100,num_of_connections_200,num_of_connections_30,num_of_connections_50,num_of_connections_ADSL,kvID_num,ttl_num_of_connections
0,7,22.409432,37.454841,ΑΡΚΑΔΙΑΣ,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,23,22.438419,37.151092,ΛΑΚΩΝΙΑΣ,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,29,22.565160,36.760664,ΛΑΚΩΝΙΑΣ,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,37,22.696999,36.831999,ΛΑΚΩΝΙΑΣ,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,50,21.817236,37.287186,ΜΕΣΣΗΝΙΑΣ,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,83,22.820381,37.607004,ΑΡΓΟΛΙΔΑΣ,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,86,22.709992,37.688783,ΑΡΓΟΛΙΔΑΣ,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,88,22.714322,37.556823,ΑΡΓΟΛΙΔΑΣ,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,92,23.129529,37.676255,ΑΡΓΟΛΙΔΑΣ,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,94,22.894504,37.537538,ΑΡΓΟΛΙΔΑΣ,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,95,22.856579,37.520562,ΑΡΓΟΛΙΔΑΣ,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
121,344,24.254198,40.848097,ΚΑΒΑΛΑΣ,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
122,346,24.512518,40.963524,ΚΑΒΑΛΑΣ,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
127,352,23.951981,40.777216,ΚΑΒΑΛΑΣ,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
129,354,24.024575,40.833367,ΚΑΒΑΛΑΣ,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
130,355,24.709862,40.779688,ΚΑΒΑΛΑΣ,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
131,357,24.730177,40.719341,ΚΑΒΑΛΑΣ,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
133,359,24.639478,40.950713,ΚΑΒΑΛΑΣ,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
134,361,24.744116,41.062406,ΚΑΒΑΛΑΣ,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
135,363,24.705607,41.023802,ΚΑΒΑΛΑΣ,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
136,364,24.670621,40.904421,ΚΑΒΑΛΑΣ,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
138,369,24.382482,41.012758,ΚΑΒΑΛΑΣ,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
140,371,24.267502,41.137132,ΔΡΑΜΑΣ,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
142,373,24.039821,41.120518,ΔΡΑΜΑΣ,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
146,378,24.209785,41.013235,ΔΡΑΜΑΣ,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
148,381,24.289996,41.099731,ΔΡΑΜΑΣ,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
150,383,24.309536,41.167753,ΔΡΑΜΑΣ,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
151,384,24.107068,41.189193,ΔΡΑΜΑΣ,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
152,390,23.927608,41.133101,ΔΡΑΜΑΣ,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
153,391,23.931213,41.190353,ΔΡΑΜΑΣ,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
154,392,24.014836,41.197361,ΔΡΑΜΑΣ,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
155,393,23.971580,41.178034,ΔΡΑΜΑΣ,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
156,395,25.288517,41.090312,ΡΟΔΟΠΗΣ,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
159,407,25.064807,41.122518,ΡΟΔΟΠΗΣ,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
161,411,24.952676,40.981036,ΞΑΝΘΗΣ,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
167,418,26.047202,40.883438,ΕΒΡΟΥ,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
168,421,26.512198,41.561336,ΕΒΡΟΥ,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
169,422,26.474718,41.647772,ΕΒΡΟΥ,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
170,423,26.455461,41.513251,ΕΒΡΟΥ,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
172,425,26.422321,41.622417,ΕΒΡΟΥ,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
173,430,26.225711,41.128584,ΕΒΡΟΥ,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
174,431,26.295684,41.155819,ΕΒΡΟΥ,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
175,432,26.198951,41.021389,ΕΒΡΟΥ,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
176,434,26.256147,41.290430,ΕΒΡΟΥ,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
178,437,26.266700,40.959283,ΕΒΡΟΥ,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
179,438,26.332109,41.633128,ΕΒΡΟΥ,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
237,589,21.295332,37.822460,ΗΛΕΙΑΣ,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
238,590,21.318218,37.978296,ΗΛΕΙΑΣ,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
239,591,21.203382,37.908548,ΗΛΕΙΑΣ,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
274,664,22.802480,41.165153,ΚΙΛΚΙΣ,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
276,666,22.816835,40.889842,ΚΙΛΚΙΣ,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
278,669,22.845477,41.101991,ΚΙΛΚΙΣ,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
280,675,23.584480,41.053192,ΣΕΡΡΩΝ,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
282,677,23.649652,41.059585,ΣΕΡΡΩΝ,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
283,679,23.361722,41.022626,ΣΕΡΡΩΝ,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
284,680,23.423819,40.956932,ΣΕΡΡΩΝ,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
285,681,23.779842,41.027392,ΣΕΡΡΩΝ,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
286,682,24.038375,40.974124,ΣΕΡΡΩΝ,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
287,683,23.904782,40.871870,ΣΕΡΡΩΝ,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
288,685,23.292851,41.274635,ΣΕΡΡΩΝ,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
289,688,23.696329,40.367747,ΧΑΛΚΙΔΙΚΗΣ,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
290,689,23.350993,40.512535,ΧΑΛΚΙΔΙΚΗΣ,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
291,690,23.543729,40.294929,ΧΑΛΚΙΔΙΚΗΣ,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
292,692,23.681483,40.443166,ΧΑΛΚΙΔΙΚΗΣ,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
293,693,23.401622,39.972045,ΧΑΛΚΙΔΙΚΗΣ,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
294,694,23.395349,40.133018,ΧΑΛΚΙΔΙΚΗΣ,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
295,695,23.616935,39.987516,ΧΑΛΚΙΔΙΚΗΣ,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
324,750,24.143041,35.382570,ΧΑΝΙΩΝ,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
326,755,24.052374,35.448660,ΧΑΝΙΩΝ,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
333,774,24.615782,35.368970,ΡΕΘΥΜΝΗΣ,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
334,777,24.691636,35.417439,ΡΕΘΥΜΝΗΣ,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
348,810,26.497682,39.180653,ΛΕΣΒΟΥ,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
349,811,26.461758,39.212465,ΛΕΣΒΟΥ,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
351,816,26.105543,39.248581,ΛΕΣΒΟΥ,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
352,818,26.371120,39.080086,ΛΕΣΒΟΥ,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
353,819,26.047733,39.223582,ΛΕΣΒΟΥ,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
354,821,26.335228,39.309691,ΛΕΣΒΟΥ,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
356,824,26.133776,39.291799,ΛΕΣΒΟΥ,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
357,825,26.216615,39.309228,ΛΕΣΒΟΥ,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
358,826,26.183963,39.081404,ΛΕΣΒΟΥ,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
359,831,26.816023,37.807324,ΣΑΜΟΥ,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
360,832,26.848230,37.785091,ΣΑΜΟΥ,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
361,833,26.910694,37.725692,ΣΑΜΟΥ,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
362,834,26.805354,37.711749,ΣΑΜΟΥ,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
363,835,26.746917,37.708326,ΣΑΜΟΥ,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
364,840,26.094434,38.391379,ΧΙΟΥ,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
365,841,26.099523,38.334261,ΧΙΟΥ,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
366,845,26.132212,38.404553,ΧΙΟΥ,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
367,846,26.119122,38.473871,ΧΙΟΥ,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
373,859,27.098239,36.809446,ΔΩΔΕΚΑΝΗΣΟΥ,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
374,860,27.147716,36.786361,ΔΩΔΕΚΑΝΗΣΟΥ,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
376,863,26.542697,37.321855,ΔΩΔΕΚΑΝΗΣΟΥ,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
377,866,27.858906,36.225124,ΔΩΔΕΚΑΝΗΣΟΥ,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
380,873,23.154927,37.268018,ΑΤΤΙΚΗΣ,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
396,929,21.142494,37.935577,ΗΛΕΙΑΣ,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
397,931,21.311759,37.898254,ΗΛΕΙΑΣ,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
421,994,22.999752,40.690956,ΘΕΣΣΑΛΟΝΙΚΗΣ,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
424,997,23.117028,40.666070,ΘΕΣΣΑΛΟΝΙΚΗΣ,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
425,998,23.589473,40.743755,ΘΕΣΣΑΛΟΝΙΚΗΣ,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
426,999,23.386585,40.749904,ΘΕΣΣΑΛΟΝΙΚΗΣ,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
427,1000,23.190449,40.632696,ΘΕΣΣΑΛΟΝΙΚΗΣ,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
428,1002,23.285311,40.573818,ΘΕΣΣΑΛΟΝΙΚΗΣ,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
432,1008,23.358230,40.818381,ΘΕΣΣΑΛΟΝΙΚΗΣ,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
437,1014,22.709441,40.766373,ΘΕΣΣΑΛΟΝΙΚΗΣ,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
439,1016,22.771514,40.753791,ΘΕΣΣΑΛΟΝΙΚΗΣ,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
480,1075,22.664184,41.008745,ΚΙΛΚΙΣ,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
481,1076,22.908056,41.072909,ΚΙΛΚΙΣ,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
483,1081,22.772075,40.840833,ΚΙΛΚΙΣ,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
484,1083,22.920389,40.839308,ΚΙΛΚΙΣ,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
485,1084,22.871429,40.911309,ΚΙΛΚΙΣ,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
486,1085,22.831490,41.258342,ΚΙΛΚΙΣ,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
487,1086,22.782386,41.089835,ΚΙΛΚΙΣ,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
489,1091,22.571042,40.929938,ΚΙΛΚΙΣ,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
491,1095,23.462243,41.073163,ΣΕΡΡΩΝ,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
492,1096,23.393010,41.068377,ΣΕΡΡΩΝ,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
495,1100,23.407978,40.987281,ΣΕΡΡΩΝ,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
498,1103,23.616598,40.883465,ΣΕΡΡΩΝ,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
499,1105,23.869226,40.926162,ΣΕΡΡΩΝ,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
500,1106,23.830039,41.028117,ΣΕΡΡΩΝ,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
501,1107,23.997674,40.944980,ΣΕΡΡΩΝ,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
502,1108,23.396999,41.177355,ΣΕΡΡΩΝ,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
504,1113,23.281635,41.184383,ΣΕΡΡΩΝ,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
505,1114,23.086839,41.213798,ΣΕΡΡΩΝ,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
506,1115,22.998908,41.260211,ΣΕΡΡΩΝ,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
507,1116,23.534657,40.372066,ΧΑΛΚΙΔΙΚΗΣ,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
508,1117,23.448301,40.546727,ΧΑΛΚΙΔΙΚΗΣ,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
509,1118,23.440358,40.380875,ΧΑΛΚΙΔΙΚΗΣ,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
510,1119,23.443197,40.505646,ΧΑΛΚΙΔΙΚΗΣ,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
511,1120,23.597543,40.487924,ΧΑΛΚΙΔΙΚΗΣ,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
512,1122,23.652339,40.493909,ΧΑΛΚΙΔΙΚΗΣ,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
513,1123,23.434407,40.100858,ΧΑΛΚΙΔΙΚΗΣ,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
514,1126,23.522959,40.016597,ΧΑΛΚΙΔΙΚΗΣ,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
515,1128,23.284456,40.240536,ΧΑΛΚΙΔΙΚΗΣ,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
516,1131,23.879229,40.396878,ΧΑΛΚΙΔΙΚΗΣ,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
517,1132,23.925994,40.380738,ΧΑΛΚΙΔΙΚΗΣ,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
518,1133,23.983043,40.324998,ΧΑΛΚΙΔΙΚΗΣ,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
519,1134,23.756827,40.529694,ΧΑΛΚΙΔΙΚΗΣ,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
521,1136,23.698837,40.249877,ΧΑΛΚΙΔΙΚΗΣ,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
522,1138,23.669389,40.222579,ΧΑΛΚΙΔΙΚΗΣ,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
523,1140,23.944217,40.038988,ΧΑΛΚΙΔΙΚΗΣ,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
534,1162,23.561758,40.622175,ΘΕΣΣΑΛΟΝΙΚΗΣ,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
537,1168,26.611105,41.380888,ΕΒΡΟΥ,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
538,1169,23.820767,41.191766,ΔΡΑΜΑΣ,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
547,1189,26.294771,37.616138,ΣΑΜΟΥ,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
556,1200,22.535456,36.929736,ΛΑΚΩΝΙΑΣ,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
558,1204,23.601116,35.470284,ΧΑΝΙΩΝ,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
560,1206,26.092843,38.241038,ΧΙΟΥ,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
561,1207,26.104420,38.293366,ΧΙΟΥ,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
562,1208,26.106293,38.542638,ΧΙΟΥ,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
564,1211,27.949867,36.339638,ΔΩΔΕΚΑΝΗΣΟΥ,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
570,1234,24.241277,40.819792,ΚΑΒΑΛΑΣ,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
574,1243,26.208732,39.233476,ΛΕΣΒΟΥ,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
575,1244,26.199827,39.041123,ΛΕΣΒΟΥ,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
576,1245,26.178504,39.330165,ΛΕΣΒΟΥ,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
577,1247,22.001249,37.242759,ΜΕΣΣΗΝΙΑΣ,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
579,1250,25.423383,40.973582,ΡΟΔΟΠΗΣ,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
580,1251,25.277965,41.137640,ΡΟΔΟΠΗΣ,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
582,1253,25.481658,41.075581,ΡΟΔΟΠΗΣ,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
585,1259,27.204394,36.876797,ΔΩΔΕΚΑΝΗΣΟΥ,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
592,1266,21.698676,37.298981,ΜΕΣΣΗΝΙΑΣ,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
597,1277,27.160403,35.547812,ΔΩΔΕΚΑΝΗΣΟΥ,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
601,1283,23.280914,40.816012,ΘΕΣΣΑΛΟΝΙΚΗΣ,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
602,1284,23.131000,40.754821,ΘΕΣΣΑΛΟΝΙΚΗΣ,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
608,1295,21.207632,37.863915,ΗΛΕΙΑΣ,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
609,1296,21.268631,37.908799,ΗΛΕΙΑΣ,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
611,1302,24.574537,40.739595,ΚΑΒΑΛΑΣ,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
617,1316,23.207990,40.303523,ΧΑΛΚΙΔΙΚΗΣ,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
618,1320,26.529947,39.147056,ΛΕΣΒΟΥ,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
622,1327,22.866268,37.544332,ΑΡΓΟΛΙΔΑΣ,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
623,1329,23.970629,40.921783,ΣΕΡΡΩΝ,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
624,1330,23.956485,41.064632,ΣΕΡΡΩΝ,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
625,1331,23.938037,41.007265,ΣΕΡΡΩΝ,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
626,1333,23.168081,40.338859,ΧΑΛΚΙΔΙΚΗΣ,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [59]:
non_common_rows = CO_code_network_info.merge(co_coords_final, left_on="CO_code", right_on='WCRM', how='left', indicator=True)
non_common_rows = non_common_rows[non_common_rows['_merge'] == 'left_only']

# Drop the _merge column
non_common_rows = non_common_rows.drop('_merge', axis=1)

In [60]:
non_common_rows.shape

(146, 23)

In [61]:
non_common_rows

,index,CO_code,mean_Actual_Speed_100,mean_Actual_Speed_200,mean_Actual_Speed_30,mean_Actual_Speed_50,mean_Actual_Speed_ADSL,mean_disconnections_100,mean_disconnections_200,mean_disconnections_30,mean_disconnections_50,mean_disconnections_ADSL,num_of_connections_100,num_of_connections_200,num_of_connections_30,num_of_connections_50,num_of_connections_ADSL,kvID_num,ttl_num_of_connections,WCRM,longitude,latitude,Νομός Α/Κ
0,0,0,82.59,212.03,NaN,44.15,12.56,14.7,38.0,NaN,25.6,22.7,73.0,1.0,0.0,211.0,93.0,213,378.0,NaN,NaN,NaN,NaN
1,1,10,79.26,NaN,NaN,54.88,NaN,7.0,NaN,NaN,6.0,NaN,2.0,0.0,0.0,1.0,0.0,3,3.0,NaN,NaN,NaN,NaN
2,2,14,NaN,NaN,NaN,55.00,NaN,NaN,NaN,NaN,7.0,NaN,0.0,0.0,0.0,1.0,0.0,1,1.0,NaN,NaN,NaN,NaN
4,4,24,NaN,NaN,NaN,49.73,NaN,NaN,NaN,NaN,2.0,NaN,0.0,0.0,0.0,1.0,0.0,1,1.0,NaN,NaN,NaN,NaN
10,10,60,NaN,NaN,NaN,53.25,NaN,NaN,NaN,NaN,19.0,NaN,0.0,0.0,0.0,1.0,0.0,1,1.0,NaN,NaN,NaN,NaN
12,12,65,27.40,NaN,NaN,37.62,NaN,3.0,NaN,NaN,2.5,NaN,1.0,0.0,0.0,2.0,0.0,2,3.0,NaN,NaN,NaN,NaN
13,13,67,NaN,NaN,NaN,15.52,NaN,NaN,NaN,NaN,1.0,NaN,0.0,0.0,0.0,2.0,0.0,2,2.0,NaN,NaN,NaN,NaN
17,17,71,NaN,NaN,NaN,34.27,NaN,NaN,NaN,NaN,2.4,NaN,0.0,0.0,0.0,5.0,0.0,2,5.0,NaN,NaN,NaN,NaN
18,18,73,NaN,NaN,NaN,48.52,NaN,NaN,NaN,NaN,2.4,NaN,0.0,0.0,0.0,5.0,0.0,1,5.0,NaN,NaN,NaN,NaN
19,19,82,NaN,NaN,NaN,7.49,NaN,NaN,NaN,NaN,4.5,NaN,0.0,0.0,0.0,2.0,0.0,1,2.0,NaN,NaN,NaN,NaN
21,21,98,NaN,NaN,NaN,30.82,NaN,NaN,NaN,NaN,17.0,NaN,0.0,0.0,0.0,1.0,0.0,1,1.0,NaN,NaN,NaN,NaN
22,22,102,NaN,NaN,NaN,45.05,NaN,NaN,NaN,NaN,57.0,NaN,0.0,0.0,0.0,1.0,0.0,1,1.0,NaN,NaN,NaN,NaN
27,27,110,NaN,NaN,NaN,53.74,NaN,NaN,NaN,NaN,2.0,NaN,0.0,0.0,0.0,2.0,0.0,2,2.0,NaN,NaN,NaN,NaN
28,28,111,NaN,NaN,NaN,46.94,NaN,NaN,NaN,NaN,143.4,NaN,0.0,0.0,0.0,5.0,0.0,1,5.0,NaN,NaN,NaN,NaN
29,29,112,NaN,NaN,NaN,48.84,NaN,NaN,NaN,NaN,3.0,NaN,0.0,0.0,0.0,1.0,0.0,1,1.0,NaN,NaN,NaN,NaN
32,32,119,NaN,NaN,NaN,44.21,NaN,NaN,NaN,NaN,11.5,NaN,0.0,0.0,0.0,2.0,0.0,1,2.0,NaN,NaN,NaN,NaN
40,40,142,NaN,NaN,NaN,41.13,NaN,NaN,NaN,NaN,0.8,NaN,0.0,0.0,0.0,10.0,0.0,4,10.0,NaN,NaN,NaN,NaN
43,43,156,NaN,NaN,NaN,43.26,NaN,NaN,NaN,NaN,2.0,NaN,0.0,0.0,0.0,3.0,0.0,1,3.0,NaN,NaN,NaN,NaN
46,46,169,NaN,NaN,NaN,41.07,NaN,NaN,NaN,NaN,86.0,NaN,0.0,0.0,0.0,1.0,0.0,1,1.0,NaN,NaN,NaN,NaN
47,47,179,NaN,NaN,NaN,31.66,NaN,NaN,NaN,NaN,8.0,NaN,0.0,0.0,0.0,1.0,0.0,1,1.0,NaN,NaN,NaN,NaN
48,48,185,48.13,NaN,NaN,40.52,NaN,1.0,NaN,NaN,7.5,NaN,1.0,0.0,0.0,4.0,0.0,1,5.0,NaN,NaN,NaN,NaN
58,58,213,96.07,NaN,NaN,53.24,NaN,6.0,NaN,NaN,7.8,NaN,1.0,0.0,0.0,4.0,0.0,3,5.0,NaN,NaN,NaN,NaN
60,60,215,NaN,NaN,NaN,40.56,NaN,NaN,NaN,NaN,7.0,NaN,0.0,0.0,0.0,1.0,0.0,1,1.0,NaN,NaN,NaN,NaN
71,71,251,NaN,NaN,NaN,53.74,NaN,NaN,NaN,NaN,8.0,NaN,0.0,0.0,0.0,1.0,0.0,1,1.0,NaN,NaN,NaN,NaN
91,91,288,NaN,NaN,NaN,38.01,NaN,NaN,NaN,NaN,2.0,NaN,0.0,0.0,0.0,1.0,0.0,1,1.0,NaN,NaN,NaN,NaN
104,104,309,90.38,NaN,NaN,53.36,NaN,3.0,NaN,NaN,16.5,NaN,2.0,0.0,0.0,2.0,0.0,2,4.0,NaN,NaN,NaN,NaN
127,127,332,61.20,NaN,NaN,42.12,NaN,33.6,NaN,NaN,16.0,NaN,4.0,0.0,0.0,5.0,0.0,3,9.0,NaN,NaN,NaN,NaN
137,137,345,NaN,NaN,NaN,38.16,NaN,NaN,NaN,NaN,64.8,NaN,0.0,0.0,0.0,4.0,0.0,2,4.0,NaN,NaN,NaN,NaN
139,139,348,64.52,NaN,NaN,45.34,NaN,4.5,NaN,NaN,11.4,NaN,5.0,0.0,0.0,22.0,0.0,8,27.0,NaN,NaN,NaN,NaN
154,154,405,12.27,NaN,NaN,NaN,NaN,20.0,NaN,NaN,NaN,NaN,1.0,0.0,0.0,0.0,0.0,1,1.0,NaN,NaN,NaN,NaN
162,162,419,35.72,NaN,NaN,29.58,NaN,5.0,NaN,NaN,10.7,NaN,1.0,0.0,0.0,3.0,0.0,1,4.0,NaN,NaN,NaN,NaN
183,183,458,106.89,NaN,NaN,53.27,NaN,25.1,NaN,NaN,4.7,NaN,5.0,0.0,0.0,9.0,0.0,7,14.0,NaN,NaN,NaN,NaN
184,184,459,NaN,NaN,NaN,50.91,NaN,NaN,NaN,NaN,0.0,NaN,0.0,0.0,0.0,1.0,0.0,1,1.0,NaN,NaN,NaN,NaN
194,194,469,79.35,NaN,NaN,41.26,NaN,20.8,NaN,NaN,21.6,NaN,4.0,0.0,0.0,11.0,0.0,7,15.0,NaN,NaN,NaN,NaN
195,195,471,NaN,NaN,NaN,10.16,NaN,NaN,NaN,NaN,8.0,NaN,0.0,0.0,0.0,1.0,0.0,1,1.0,NaN,NaN,NaN,NaN
196,196,474,NaN,NaN,NaN,53.74,NaN,NaN,NaN,NaN,7.0,NaN,0.0,0.0,0.0,1.0,0.0,1,1.0,NaN,NaN,NaN,NaN
197,197,475,33.02,NaN,NaN,40.84,NaN,53.7,NaN,NaN,21.3,NaN,4.0,0.0,0.0,52.0,0.0,15,56.0,NaN,NaN,NaN,NaN
200,200,478,110.00,NaN,NaN,54.49,NaN,18.0,NaN,NaN,15.3,NaN,1.0,0.0,0.0,3.0,0.0,4,4.0,NaN,NaN,NaN,NaN
201,201,479,NaN,NaN,NaN,53.74,NaN,NaN,NaN,NaN,16.0,NaN,0.0,0.0,0.0,1.0,0.0,1,1.0,NaN,NaN,NaN,NaN
202,202,481,48.10,46.85,NaN,34.33,NaN,27.0,461.0,NaN,25.8,NaN,3.0,1.0,0.0,15.0,0.0,8,19.0,NaN,NaN,NaN,NaN
206,206,491,NaN,NaN,NaN,50.44,NaN,NaN,NaN,NaN,194.0,NaN,0.0,0.0,0.0,2.0,0.0,2,2.0,NaN,NaN,NaN,NaN
218,218,544,66.70,35.46,NaN,42.82,NaN,26.8,15.0,NaN,21.5,NaN,4.0,1.0,0.0,11.0,0.0,2,16.0,NaN,NaN,NaN,NaN
222,222,550,NaN,NaN,NaN,31.54,NaN,NaN,NaN,NaN,34.5,NaN,0.0,0.0,0.0,4.0,0.0,1,4.0,NaN,NaN,NaN,NaN
225,225,562,NaN,NaN,NaN,26.83,NaN,NaN,NaN,NaN,4.0,NaN,0.0,0.0,0.0,1.0,0.0,1,1.0,NaN,NaN,NaN,NaN
226,226,563,6.36,NaN,NaN,NaN,NaN,245.0,NaN,NaN,NaN,NaN,2.0,0.0,0.0,0.0,0.0,1,2.0,NaN,NaN,NaN,NaN
227,227,566,NaN,NaN,NaN,54.99,NaN,NaN,NaN,NaN,45.0,NaN,0.0,0.0,0.0,1.0,0.0,1,1.0,NaN,NaN,NaN,NaN
237,237,594,NaN,NaN,NaN,53.74,NaN,NaN,NaN,NaN,1.0,NaN,0.0,0.0,0.0,1.0,0.0,1,1.0,NaN,NaN,NaN,NaN
244,244,608,NaN,NaN,NaN,37.67,NaN,NaN,NaN,NaN,45.0,NaN,0.0,0.0,0.0,7.0,0.0,3,7.0,NaN,NaN,NaN,NaN
245,245,610,56.83,34.95,NaN,53.74,NaN,12.0,11.0,NaN,18.0,NaN,1.0,1.0,0.0,1.0,0.0,2,3.0,NaN,NaN,NaN,NaN
249,249,619,NaN,NaN,NaN,45.60,NaN,NaN,NaN,NaN,172.6,NaN,0.0,0.0,0.0,6.0,0.0,2,6.0,NaN,NaN,NaN,NaN
259,259,642,NaN,NaN,NaN,47.30,NaN,NaN,NaN,NaN,4.2,NaN,0.0,0.0,0.0,4.0,0.0,2,4.0,NaN,NaN,NaN,NaN
287,287,709,107.78,NaN,NaN,46.94,NaN,7.0,NaN,NaN,23.0,NaN,1.0,0.0,0.0,3.0,0.0,2,4.0,NaN,NaN,NaN,NaN
288,288,710,NaN,NaN,NaN,17.87,NaN,NaN,NaN,NaN,3.0,NaN,0.0,0.0,0.0,1.0,0.0,1,1.0,NaN,NaN,NaN,NaN
305,305,736,86.26,NaN,NaN,37.12,NaN,3.5,NaN,NaN,38.3,NaN,6.0,0.0,0.0,38.0,0.0,12,44.0,NaN,NaN,NaN,NaN
306,306,737,79.40,NaN,NaN,45.02,NaN,4.0,NaN,NaN,10.2,NaN,2.0,0.0,0.0,8.0,0.0,2,10.0,NaN,NaN,NaN,NaN
309,309,741,70.32,NaN,NaN,53.74,NaN,27.5,NaN,NaN,2.5,NaN,3.0,0.0,0.0,2.0,0.0,2,5.0,NaN,NaN,NaN,NaN
310,310,742,48.11,NaN,NaN,33.72,NaN,48.4,NaN,NaN,6.4,NaN,5.0,0.0,0.0,9.0,0.0,5,14.0,NaN,NaN,NaN,NaN
312,312,744,60.05,NaN,NaN,42.61,NaN,8.3,NaN,NaN,19.8,NaN,3.0,0.0,0.0,12.0,0.0,8,15.0,NaN,NaN,NaN,NaN
322,322,776,110.00,NaN,NaN,54.99,NaN,7.0,NaN,NaN,3.0,NaN,1.0,0.0,0.0,2.0,0.0,2,3.0,NaN,NaN,NaN,NaN
352,352,893,110.00,NaN,NaN,NaN,NaN,3.5,NaN,NaN,NaN,NaN,2.0,0.0,0.0,0.0,0.0,2,2.0,NaN,NaN,NaN,NaN
357,357,902,NaN,NaN,NaN,53.74,NaN,NaN,NaN,NaN,7.0,NaN,0.0,0.0,0.0,1.0,0.0,1,1.0,NaN,NaN,NaN,NaN
363,363,930,NaN,NaN,NaN,48.72,NaN,NaN,NaN,NaN,2.0,NaN,0.0,0.0,0.0,1.0,0.0,1,1.0,NaN,NaN,NaN,NaN
364,364,934,NaN,NaN,NaN,49.10,NaN,NaN,NaN,NaN,26.2,NaN,0.0,0.0,0.0,6.0,0.0,4,6.0,NaN,NaN,NaN,NaN
366,366,936,NaN,NaN,NaN,35.96,NaN,NaN,NaN,NaN,38.0,NaN,0.0,0.0,0.0,2.0,0.0,1,2.0,NaN,NaN,NaN,NaN
416,416,1040,NaN,NaN,NaN,34.85,NaN,NaN,NaN,NaN,5.8,NaN,0.0,0.0,0.0,4.0,0.0,2,4.0,NaN,NaN,NaN,NaN
418,418,1043,95.09,NaN,NaN,37.44,NaN,18.0,NaN,NaN,100.0,NaN,1.0,0.0,0.0,9.0,0.0,4,10.0,NaN,NaN,NaN,NaN
422,422,1049,NaN,NaN,NaN,22.73,NaN,NaN,NaN,NaN,55.9,NaN,0.0,0.0,0.0,8.0,0.0,6,8.0,NaN,NaN,NaN,NaN
424,424,1053,NaN,NaN,NaN,26.37,NaN,NaN,NaN,NaN,8.0,NaN,0.0,0.0,0.0,1.0,0.0,1,1.0,NaN,NaN,NaN,NaN
451,451,1130,46.91,NaN,NaN,41.21,NaN,120.0,NaN,NaN,94.0,NaN,1.0,0.0,0.0,3.0,0.0,4,4.0,NaN,NaN,NaN,NaN
455,455,1144,NaN,NaN,NaN,19.62,NaN,NaN,NaN,NaN,6.5,NaN,0.0,0.0,0.0,2.0,0.0,1,2.0,NaN,NaN,NaN,NaN
462,462,1158,NaN,NaN,NaN,36.26,NaN,NaN,NaN,NaN,14.0,NaN,0.0,0.0,0.0,1.0,0.0,1,1.0,NaN,NaN,NaN,NaN
466,466,1166,NaN,NaN,NaN,50.63,NaN,NaN,NaN,NaN,3.6,NaN,0.0,0.0,0.0,5.0,0.0,3,5.0,NaN,NaN,NaN,NaN
469,469,1173,NaN,NaN,NaN,55.00,NaN,NaN,NaN,NaN,6.0,NaN,0.0,0.0,0.0,1.0,0.0,1,1.0,NaN,NaN,NaN,NaN
492,492,1226,NaN,NaN,NaN,44.91,NaN,NaN,NaN,NaN,2.0,NaN,0.0,0.0,0.0,2.0,0.0,2,2.0,NaN,NaN,NaN,NaN
494,494,1233,NaN,NaN,NaN,42.54,NaN,NaN,NaN,NaN,495.0,NaN,0.0,0.0,0.0,1.0,0.0,1,1.0,NaN,NaN,NaN,NaN
498,498,1246,40.09,NaN,NaN,36.63,NaN,23.3,NaN,NaN,10.0,NaN,9.0,0.0,0.0,17.0,0.0,5,26.0,NaN,NaN,NaN,NaN
501,501,1254,80.64,18.94,NaN,45.37,NaN,3.6,75.5,NaN,16.4,NaN,6.0,2.0,0.0,25.0,0.0,7,33.0,NaN,NaN,NaN,NaN
518,518,1286,NaN,NaN,NaN,53.74,NaN,NaN,NaN,NaN,2.0,NaN,0.0,0.0,0.0,1.0,0.0,1,1.0,NaN,NaN,NaN,NaN
524,524,1304,38.96,NaN,NaN,43.37,NaN,2.0,NaN,NaN,43.1,NaN,1.0,0.0,0.0,16.0,0.0,5,17.0,NaN,NaN,NaN,NaN
527,527,1309,88.79,126.00,NaN,33.76,NaN,11.8,15.0,NaN,41.2,NaN,4.0,1.0,0.0,5.0,0.0,5,10.0,NaN,NaN,NaN,NaN
528,528,1311,NaN,NaN,NaN,54.96,NaN,NaN,NaN,NaN,0.5,NaN,0.0,0.0,0.0,2.0,0.0,2,2.0,NaN,NaN,NaN,NaN
535,535,1328,NaN,NaN,NaN,46.21,NaN,NaN,NaN,NaN,8.5,NaN,0.0,0.0,0.0,2.0,0.0,1,2.0,NaN,NaN,NaN,NaN
536,536,1338,77.44,NaN,NaN,26.69,NaN,41.0,NaN,NaN,201.0,NaN,1.0,0.0,0.0,1.0,0.0,2,2.0,NaN,NaN,NaN,NaN
537,537,1339,NaN,NaN,NaN,32.57,NaN,NaN,NaN,NaN,15.4,NaN,0.0,0.0,0.0,8.0,0.0,4,8.0,NaN,NaN,NaN,NaN
541,541,1352,NaN,NaN,NaN,14.98,NaN,NaN,NaN,NaN,6.0,NaN,0.0,0.0,0.0,1.0,0.0,1,1.0,NaN,NaN,NaN,NaN
548,548,1360,NaN,NaN,NaN,42.43,NaN,NaN,NaN,NaN,90.0,NaN,0.0,0.0,0.0,2.0,0.0,1,2.0,NaN,NaN,NaN,NaN
553,553,1373,49.27,NaN,NaN,47.92,NaN,13.0,NaN,NaN,20.2,NaN,1.0,0.0,0.0,4.0,0.0,4,5.0,NaN,NaN,NaN,NaN
554,554,1374,NaN,NaN,NaN,19.94,NaN,NaN,NaN,NaN,14.0,NaN,0.0,0.0,0.0,1.0,0.0,1,1.0,NaN,NaN,NaN,NaN
555,555,1375,79.87,NaN,NaN,53.75,NaN,7.5,NaN,NaN,3.7,NaN,2.0,0.0,0.0,3.0,0.0,1,5.0,NaN,NaN,NaN,NaN
557,557,1388,56.76,NaN,NaN,NaN,NaN,3.0,NaN,NaN,NaN,NaN,1.0,0.0,0.0,0.0,0.0,1,1.0,NaN,NaN,NaN,NaN
559,559,1396,NaN,NaN,NaN,29.21,NaN,NaN,NaN,NaN,6.0,NaN,0.0,0.0,0.0,1.0,0.0,1,1.0,NaN,NaN,NaN,NaN
560,560,1397,NaN,NaN,NaN,54.99,NaN,NaN,NaN,NaN,9.0,NaN,0.0,0.0,0.0,1.0,0.0,1,1.0,NaN,NaN,NaN,NaN
569,569,1415,76.52,NaN,NaN,51.98,NaN,8.0,NaN,NaN,67.7,NaN,2.0,0.0,0.0,3.0,0.0,3,5.0,NaN,NaN,NaN,NaN
572,572,1419,NaN,NaN,NaN,53.74,NaN,NaN,NaN,NaN,22.0,NaN,0.0,0.0,0.0,1.0,0.0,1,1.0,NaN,NaN,NaN,NaN
575,575,1423,66.06,NaN,NaN,52.48,NaN,2.0,NaN,NaN,3.0,NaN,1.0,0.0,0.0,3.0,0.0,2,4.0,NaN,NaN,NaN,NaN
586,586,1439,110.00,NaN,NaN,NaN,NaN,3.0,NaN,NaN,NaN,NaN,1.0,0.0,0.0,0.0,0.0,1,1.0,NaN,NaN,NaN,NaN
602,602,1473,107.79,NaN,NaN,33.87,NaN,3.0,NaN,NaN,275.0,NaN,1.0,0.0,0.0,1.0,0.0,1,2.0,NaN,NaN,NaN,NaN
603,603,1474,75.11,NaN,NaN,46.33,NaN,19.0,NaN,NaN,21.0,NaN,1.0,0.0,0.0,3.0,0.0,2,4.0,NaN,NaN,NaN,NaN
610,610,1492,NaN,NaN,NaN,30.67,NaN,NaN,NaN,NaN,6.5,NaN,0.0,0.0,0.0,2.0,0.0,1,2.0,NaN,NaN,NaN,NaN
611,611,1493,NaN,NaN,NaN,55.00,NaN,NaN,NaN,NaN,1.0,NaN,0.0,0.0,0.0,1.0,0.0,1,1.0,NaN,NaN,NaN,NaN
612,612,1494,NaN,NaN,NaN,28.68,NaN,NaN,NaN,NaN,51.5,NaN,0.0,0.0,0.0,3.0,0.0,2,3.0,NaN,NaN,NaN,NaN
613,613,1495,NaN,NaN,NaN,53.06,NaN,NaN,NaN,NaN,5.7,NaN,0.0,0.0,0.0,3.0,0.0,1,3.0,NaN,NaN,NaN,NaN
614,614,1502,58.92,NaN,NaN,39.12,NaN,3.0,NaN,NaN,12.1,NaN,1.0,0.0,0.0,6.0,0.0,3,7.0,NaN,NaN,NaN,NaN
619,619,1511,49.07,NaN,NaN,34.26,NaN,96.7,NaN,NaN,123.4,NaN,12.0,0.0,0.0,22.0,0.0,7,34.0,NaN,NaN,NaN,NaN
623,623,1518,NaN,NaN,NaN,53.74,NaN,NaN,NaN,NaN,1.5,NaN,0.0,0.0,0.0,2.0,0.0,1,2.0,NaN,NaN,NaN,NaN
663,663,1589,75.43,NaN,NaN,45.87,NaN,8.7,NaN,NaN,5.9,NaN,4.0,0.0,0.0,6.0,0.0,6,10.0,NaN,NaN,NaN,NaN
672,672,1604,87.86,NaN,NaN,47.86,NaN,3.0,NaN,NaN,14.0,NaN,2.0,0.0,0.0,9.0,0.0,3,11.0,NaN,NaN,NaN,NaN
675,675,1608,NaN,NaN,NaN,53.74,NaN,NaN,NaN,NaN,18.0,NaN,0.0,0.0,0.0,1.0,0.0,1,1.0,NaN,NaN,NaN,NaN
677,677,1611,54.90,NaN,NaN,46.87,NaN,148.8,NaN,NaN,21.6,NaN,3.0,0.0,0.0,14.0,0.0,3,17.0,NaN,NaN,NaN,NaN
684,684,1628,NaN,NaN,NaN,32.36,NaN,NaN,NaN,NaN,5.0,NaN,0.0,0.0,0.0,1.0,0.0,1,1.0,NaN,NaN,NaN,NaN
686,686,1633,79.67,NaN,NaN,47.00,NaN,3.0,NaN,NaN,10.8,NaN,1.0,0.0,0.0,7.0,0.0,4,8.0,NaN,NaN,NaN,NaN
690,690,1644,NaN,NaN,NaN,53.41,NaN,NaN,NaN,NaN,68.5,NaN,0.0,0.0,0.0,2.0,0.0,1,2.0,NaN,NaN,NaN,NaN
693,693,1651,74.53,19.20,NaN,45.51,NaN,10.8,66.0,NaN,15.1,NaN,3.0,1.0,0.0,15.0,0.0,4,19.0,NaN,NaN,NaN,NaN
720,720,1718,NaN,NaN,NaN,55.00,NaN,NaN,NaN,NaN,6.0,NaN,0.0,0.0,0.0,1.0,0.0,1,1.0,NaN,NaN,NaN,NaN
721,721,1724,NaN,NaN,NaN,47.72,NaN,NaN,NaN,NaN,0.5,NaN,0.0,0.0,0.0,2.0,0.0,2,2.0,NaN,NaN,NaN,NaN
722,722,1727,NaN,NaN,NaN,41.35,NaN,NaN,NaN,NaN,4.0,NaN,0.0,0.0,0.0,1.0,0.0,1,1.0,NaN,NaN,NaN,NaN
725,725,1733,NaN,NaN,NaN,42.76,NaN,NaN,NaN,NaN,60.5,NaN,0.0,0.0,0.0,3.0,0.0,2,3.0,NaN,NaN,NaN,NaN
726,726,1738,NaN,NaN,NaN,53.74,NaN,NaN,NaN,NaN,5.0,NaN,0.0,0.0,0.0,2.0,0.0,1,2.0,NaN,NaN,NaN,NaN
727,727,1744,NaN,NaN,NaN,44.01,NaN,NaN,NaN,NaN,65.5,NaN,0.0,0.0,0.0,2.0,0.0,1,2.0,NaN,NaN,NaN,NaN
728,728,1745,NaN,NaN,NaN,17.30,NaN,NaN,NaN,NaN,14.0,NaN,0.0,0.0,0.0,1.0,0.0,1,1.0,NaN,NaN,NaN,NaN
742,742,1828,95.80,NaN,NaN,53.74,NaN,3.0,NaN,NaN,2.0,NaN,1.0,0.0,0.0,3.0,0.0,2,4.0,NaN,NaN,NaN,NaN
744,744,1831,94.50,NaN,NaN,50.74,NaN,4.5,NaN,NaN,6.8,NaN,5.0,0.0,0.0,9.0,0.0,7,14.0,NaN,NaN,NaN,NaN
745,745,1833,81.79,NaN,NaN,43.21,NaN,7.3,NaN,NaN,24.9,NaN,3.0,0.0,0.0,15.0,0.0,6,18.0,NaN,NaN,NaN,NaN
748,748,1848,NaN,NaN,NaN,55.00,NaN,NaN,NaN,NaN,2.0,NaN,0.0,0.0,0.0,2.0,0.0,2,2.0,NaN,NaN,NaN,NaN
762,762,1874,77.08,NaN,NaN,41.10,NaN,0.0,NaN,NaN,211.0,NaN,1.0,0.0,0.0,1.0,0.0,2,2.0,NaN,NaN,NaN,NaN
766,766,1885,83.20,NaN,NaN,47.96,5.49,14.0,NaN,NaN,9.2,53.0,2.0,0.0,0.0,17.0,1.0,6,20.0,NaN,NaN,NaN,NaN
767,767,1893,67.74,NaN,NaN,53.10,NaN,8.0,NaN,NaN,7.0,NaN,2.0,0.0,0.0,7.0,0.0,3,9.0,NaN,NaN,NaN,NaN
769,769,1895,NaN,NaN,NaN,40.22,NaN,NaN,NaN,NaN,9.0,NaN,0.0,0.0,0.0,2.0,0.0,1,2.0,NaN,NaN,NaN,NaN
776,776,1921,29.22,NaN,NaN,51.82,NaN,33.0,NaN,NaN,25.6,NaN,1.0,0.0,0.0,5.0,0.0,4,6.0,NaN,NaN,NaN,NaN
781,781,1928,107.79,NaN,NaN,42.82,NaN,4.0,NaN,NaN,12.3,NaN,1.0,0.0,0.0,3.0,0.0,3,4.0,NaN,NaN,NaN,NaN
785,785,1935,NaN,NaN,NaN,45.41,NaN,NaN,NaN,NaN,97.7,NaN,0.0,0.0,0.0,5.0,0.0,3,5.0,NaN,NaN,NaN,NaN
790,790,1958,NaN,NaN,NaN,41.76,NaN,NaN,NaN,NaN,10.0,NaN,0.0,0.0,0.0,1.0,0.0,1,1.0,NaN,NaN,NaN,NaN
794,794,1973,NaN,NaN,NaN,52.41,NaN,NaN,NaN,NaN,11.0,NaN,0.0,0.0,0.0,1.0,0.0,1,1.0,NaN,NaN,NaN,NaN
799,799,2007,109.98,NaN,NaN,55.00,NaN,1.0,NaN,NaN,1.0,NaN,1.0,0.0,0.0,1.0,0.0,2,2.0,NaN,NaN,NaN,NaN
800,800,2009,27.49,NaN,NaN,NaN,NaN,20.0,NaN,NaN,NaN,NaN,1.0,0.0,0.0,0.0,0.0,1,1.0,NaN,NaN,NaN,NaN
802,802,2015,NaN,NaN,NaN,18.06,NaN,NaN,NaN,NaN,3.0,NaN,0.0,0.0,0.0,1.0,0.0,1,1.0,NaN,NaN,NaN,NaN
803,803,2018,NaN,NaN,NaN,37.91,NaN,NaN,NaN,NaN,9.0,NaN,0.0,0.0,0.0,1.0,0.0,1,1.0,NaN,NaN,NaN,NaN
805,805,2023,61.13,58.65,NaN,49.86,NaN,17.0,3.0,NaN,39.0,NaN,4.0,1.0,0.0,20.0,0.0,7,25.0,NaN,NaN,NaN,NaN
806,806,2029,62.86,NaN,NaN,46.19,NaN,8.0,NaN,NaN,10.5,NaN,2.0,0.0,0.0,7.0,0.0,4,9.0,NaN,NaN,NaN,NaN
810,810,2046,67.16,NaN,NaN,53.74,NaN,10.0,NaN,NaN,2.0,NaN,1.0,0.0,0.0,1.0,0.0,2,2.0,NaN,NaN,NaN,NaN
811,811,2048,25.36,NaN,NaN,35.64,NaN,373.0,NaN,NaN,15.7,NaN,1.0,0.0,0.0,21.0,0.0,5,22.0,NaN,NaN,NaN,NaN
814,814,2052,52.97,NaN,NaN,38.53,NaN,2.7,NaN,NaN,18.1,NaN,8.0,0.0,0.0,18.0,0.0,3,26.0,NaN,NaN,NaN,NaN
833,833,2099,72.17,NaN,NaN,42.78,NaN,16.0,NaN,NaN,16.7,NaN,1.0,0.0,0.0,16.0,0.0,3,17.0,NaN,NaN,NaN,NaN
834,834,2120,NaN,NaN,NaN,24.51,NaN,NaN,NaN,NaN,16.4,NaN,0.0,0.0,0.0,6.0,0.0,2,6.0,NaN,NaN,NaN,NaN
835,835,2129,NaN,NaN,NaN,36.63,NaN,NaN,NaN,NaN,16.5,NaN,0.0,0.0,0.0,11.0,0.0,2,11.0,NaN,NaN,NaN,NaN
836,836,2269,56.06,NaN,NaN,50.19,NaN,39.5,NaN,NaN,46.0,NaN,2.0,0.0,0.0,2.0,0.0,1,4.0,NaN,NaN,NaN,NaN

# Merge with latlong

In [62]:
co_coords_final["WCRM"].nunique()
CO_code_network_info["CO_code"].nunique()

971

841

In [63]:
CO_code_network_coords = co_coords_final.merge(CO_code_network_info, left_on= "WCRM", right_on="CO_code")

In [64]:
CO_code_network_coords.head()

,WCRM,longitude,latitude,Νομός Α/Κ,index,CO_code,mean_Actual_Speed_100,mean_Actual_Speed_200,mean_Actual_Speed_30,mean_Actual_Speed_50,mean_Actual_Speed_ADSL,mean_disconnections_100,mean_disconnections_200,mean_disconnections_30,mean_disconnections_50,mean_disconnections_ADSL,num_of_connections_100,num_of_connections_200,num_of_connections_30,num_of_connections_50,num_of_connections_ADSL,kvID_num,ttl_num_of_connections
0,16,22.853874,37.244403,ΑΡΚΑΔΙΑΣ,3,16,18.54,NaN,NaN,54.70,NaN,7.0,NaN,NaN,14.0,NaN,1.0,0.0,0.0,1.0,0.0,2,2.0
1,27,22.452459,36.959996,ΛΑΚΩΝΙΑΣ,5,27,39.29,NaN,NaN,49.25,NaN,171.0,NaN,NaN,316.5,NaN,1.0,0.0,0.0,2.0,0.0,1,3.0
2,45,22.078575,37.047754,ΜΕΣΣΗΝΙΑΣ,6,45,107.77,NaN,NaN,48.51,NaN,5.0,NaN,NaN,114.5,NaN,1.0,0.0,0.0,3.0,0.0,2,4.0
3,47,22.111926,37.034498,ΜΕΣΣΗΝΙΑΣ,7,47,90.75,133.71,27.13,51.45,11.46,16.0,77.0,26.7,9.6,31.2,1141.0,15.0,315.0,1562.0,1641.0,196,4674.0
4,56,21.941240,37.003638,ΜΕΣΣΗΝΙΑΣ,8,56,NaN,NaN,NaN,27.78,NaN,NaN,NaN,NaN,18.0,NaN,0.0,0.0,0.0,1.0,0.0,1,1.0

In [65]:
CO_code_network_coords.shape

(695, 23)

In [66]:
#CO_code_network_coords = CO_code_network_coords.rename(columns={"Κωδικός Α/Κ WCRM LLU": "CO_code"})

In [67]:
#CO_code_network_coords

In [68]:
#CO_code_network_coords = CO_code_network_coords.fillna("NO customers")

In [69]:
#CO_code_network_coords

In [70]:
CO_code_network_coords[CO_code_network_coords.duplicated("CO_code")]

Empty DataFrame
Columns: [WCRM, longitude, latitude, Νομός Α/Κ, index, CO_code, mean_Actual_Speed_100, mean_Actual_Speed_200, mean_Actual_Speed_30, mean_Actual_Speed_50, mean_Actual_Speed_ADSL, mean_disconnections_100, mean_disconnections_200, mean_disconnections_30, mean_disconnections_50, mean_disconnections_ADSL, num_of_connections_100, num_of_connections_200, num_of_connections_30, num_of_connections_50, num_of_connections_ADSL, kvID_num, ttl_num_of_connections]
Index: []

In [71]:
CO_code_network_coords.dtypes

WCRM                          int64
longitude                   float64
latitude                    float64
Νομός Α/Κ                    object
index                         int64
CO_code                       int64
mean_Actual_Speed_100       float64
mean_Actual_Speed_200       float64
mean_Actual_Speed_30        float64
mean_Actual_Speed_50        float64
mean_Actual_Speed_ADSL      float64
mean_disconnections_100     float64
mean_disconnections_200     float64
mean_disconnections_30      float64
mean_disconnections_50      float64
mean_disconnections_ADSL    float64
num_of_connections_100      float64
num_of_connections_200      float64
num_of_connections_30       float64
num_of_connections_50       float64
num_of_connections_ADSL     float64
kvID_num                      int64
ttl_num_of_connections      float64
dtype: object

# Merge with product

In [72]:
CO_code_network_coords.shape

(695, 23)

In [73]:
CO_code_network_coords_product = CO_code_network_coords.merge(vf_product, left_on="CO_code", right_on="CO code")

In [74]:
CO_code_network_coords_product.shape

(691, 32)

In [75]:
CO_code_network_coords_product

,WCRM,longitude,latitude,Νομός Α/Κ,index,CO_code,mean_Actual_Speed_100,mean_Actual_Speed_200,mean_Actual_Speed_30,mean_Actual_Speed_50,mean_Actual_Speed_ADSL,mean_disconnections_100,mean_disconnections_200,mean_disconnections_30,mean_disconnections_50,mean_disconnections_ADSL,num_of_connections_100,num_of_connections_200,num_of_connections_30,num_of_connections_50,num_of_connections_ADSL,kvID_num,ttl_num_of_connections,CO code,OKSY C,NGA availability,VF base (retail services),VF MS,submitted 12m,created 12m,submitted 6m,created 6m
0,16,22.853874,37.244403,ΑΡΚΑΔΙΑΣ,3,16,18.54,NaN,NaN,54.70,NaN,7.0,NaN,NaN,14.0,NaN,1.0,0.0,0.0,1.0,0.0,2,2.0,16,ACTIVE,0.466855,2.0,0.003206,2.0,2.0,0.0,0.0
1,27,22.452459,36.959996,ΛΑΚΩΝΙΑΣ,5,27,39.29,NaN,NaN,49.25,NaN,171.0,NaN,NaN,316.5,NaN,1.0,0.0,0.0,2.0,0.0,1,3.0,27,ACTIVE,0.401204,4.0,0.004559,1.0,1.0,0.0,0.0
2,45,22.078575,37.047754,ΜΕΣΣΗΝΙΑΣ,6,45,107.77,NaN,NaN,48.51,NaN,5.0,NaN,NaN,114.5,NaN,1.0,0.0,0.0,3.0,0.0,2,4.0,45,ACTIVE,0.367288,5.0,0.008152,10.0,12.0,5.0,6.0
3,47,22.111926,37.034498,ΜΕΣΣΗΝΙΑΣ,7,47,90.75,133.71,27.13,51.45,11.46,16.0,77.0,26.7,9.6,31.2,1141.0,15.0,315.0,1562.0,1641.0,196,4674.0,47,ACTIVE,0.737261,5275.0,0.208353,834.0,988.0,435.0,506.0
4,56,21.941240,37.003638,ΜΕΣΣΗΝΙΑΣ,8,56,NaN,NaN,NaN,27.78,NaN,NaN,NaN,NaN,18.0,NaN,0.0,0.0,0.0,1.0,0.0,1,1.0,56,ACTIVE,0.278388,1.0,0.004163,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
686,2082,24.933898,37.436261,ΚΥΚΛΑΔΩΝ,829,2082,80.17,NaN,NaN,44.79,14.52,14.0,NaN,NaN,14.6,27.4,70.0,0.0,0.0,169.0,213.0,33,452.0,2082,ACTIVE,0.720012,497.0,0.174151,58.0,69.0,28.0,36.0
687,2083,22.521566,40.756624,ΠΕΛΛΗΣ,830,2083,NaN,NaN,NaN,NaN,13.45,NaN,NaN,NaN,NaN,6.5,0.0,0.0,0.0,0.0,86.0,6,86.0,2083,Inactive,0.000000,288.0,0.466200,NaN,NaN,NaN,NaN
688,2087,28.211207,36.380284,ΔΩΔΕΚΑΝΗΣΟΥ,831,2087,81.18,196.74,NaN,52.08,NaN,40.2,8.0,NaN,9.7,NaN,14.0,1.0,0.0,25.0,0.0,10,40.0,2087,ACTIVE,0.920611,54.0,0.046842,36.0,46.0,27.0,33.0
689,2091,21.485059,38.608638,ΑΙΤΩΛΟΑΚΑΡΝΑΝΙΑΣ,832,2091,71.59,52.34,NaN,49.95,15.88,25.5,14.5,NaN,18.1,58.9,51.0,3.0,0.0,113.0,90.0,13,257.0,2091,ACTIVE,0.934161,277.0,0.391022,30.0,36.0,14.0,17.0
690,2079,25.037444,35.396333,ΛΥΓΑΡΙΑ,827,2079,NaN,NaN,NaN,55.00,NaN,NaN,NaN,NaN,4.0,NaN,0.0,0.0,0.0,1.0,0.0,1,1.0,2079,ACTIVE,0.419355,8.0,0.029326,3.0,3.0,2.0,2.0

In [76]:
CO_code_network_coords_product = CO_code_network_coords_product.drop("WCRM",axis=1)

In [77]:
CO_code_network_coords_product["VF MS"] = CO_code_network_coords_product["VF MS"].round(2)
CO_code_network_coords_product["NGA availability"] = CO_code_network_coords_product["NGA availability"].round(2)

In [78]:
CO_code_network_coords_product["icon"] = 'home'

In [79]:
CO_code_network_coords_product_final = CO_code_network_coords_product

In [80]:
CO_code_network_coords_product_final.head(10)

,longitude,latitude,Νομός Α/Κ,index,CO_code,mean_Actual_Speed_100,mean_Actual_Speed_200,mean_Actual_Speed_30,mean_Actual_Speed_50,mean_Actual_Speed_ADSL,mean_disconnections_100,mean_disconnections_200,mean_disconnections_30,mean_disconnections_50,mean_disconnections_ADSL,num_of_connections_100,num_of_connections_200,num_of_connections_30,num_of_connections_50,num_of_connections_ADSL,kvID_num,ttl_num_of_connections,CO code,OKSY C,NGA availability,VF base (retail services),VF MS,submitted 12m,created 12m,submitted 6m,created 6m,icon
0,22.853874,37.244403,ΑΡΚΑΔΙΑΣ,3,16,18.54,NaN,NaN,54.70,NaN,7.0,NaN,NaN,14.0,NaN,1.0,0.0,0.0,1.0,0.0,2,2.0,16,ACTIVE,0.47,2.0,0.00,2.0,2.0,0.0,0.0,home
1,22.452459,36.959996,ΛΑΚΩΝΙΑΣ,5,27,39.29,NaN,NaN,49.25,NaN,171.0,NaN,NaN,316.5,NaN,1.0,0.0,0.0,2.0,0.0,1,3.0,27,ACTIVE,0.40,4.0,0.00,1.0,1.0,0.0,0.0,home
2,22.078575,37.047754,ΜΕΣΣΗΝΙΑΣ,6,45,107.77,NaN,NaN,48.51,NaN,5.0,NaN,NaN,114.5,NaN,1.0,0.0,0.0,3.0,0.0,2,4.0,45,ACTIVE,0.37,5.0,0.01,10.0,12.0,5.0,6.0,home
3,22.111926,37.034498,ΜΕΣΣΗΝΙΑΣ,7,47,90.75,133.71,27.13,51.45,11.46,16.0,77.0,26.7,9.6,31.2,1141.0,15.0,315.0,1562.0,1641.0,196,4674.0,47,ACTIVE,0.74,5275.0,0.21,834.0,988.0,435.0,506.0,home
4,21.941240,37.003638,ΜΕΣΣΗΝΙΑΣ,8,56,NaN,NaN,NaN,27.78,NaN,NaN,NaN,NaN,18.0,NaN,0.0,0.0,0.0,1.0,0.0,1,1.0,56,ACTIVE,0.28,1.0,0.00,NaN,NaN,NaN,NaN,home
5,21.929222,36.957189,ΜΕΣΣΗΝΙΑΣ,9,59,49.32,NaN,NaN,47.54,12.84,19.1,NaN,NaN,11.1,44.0,6.0,0.0,0.0,14.0,108.0,10,128.0,59,ACTIVE,0.22,161.0,0.23,7.0,11.0,4.0,5.0,home
6,21.695455,36.912130,ΜΕΣΣΗΝΙΑΣ,11,62,59.60,NaN,NaN,53.41,16.13,8.4,NaN,NaN,47.0,26.8,6.0,0.0,0.0,8.0,264.0,16,278.0,62,ACTIVE,0.23,351.0,0.26,26.0,38.0,18.0,24.0,home
7,22.882110,37.906294,ΚΟΡΙΝΘΙΑΣ,14,68,31.59,NaN,NaN,48.83,11.42,12.3,NaN,NaN,40.4,23.8,14.0,0.0,0.0,14.0,114.0,10,142.0,68,ACTIVE,0.30,194.0,0.26,20.0,26.0,10.0,15.0,home
8,22.930735,37.938625,ΚΟΡΙΝΘΙΑΣ,15,69,85.10,NaN,30.84,48.58,13.24,25.3,NaN,8.1,21.5,22.8,505.0,0.0,27.0,1025.0,1091.0,130,2648.0,69,ACTIVE,0.73,3092.0,0.24,440.0,604.0,248.0,301.0,home
9,22.840894,37.937308,ΚΟΡΙΝΘΙΑΣ,16,70,69.60,104.33,NaN,44.56,10.70,13.0,15.8,NaN,20.0,27.2,82.0,4.0,0.0,201.0,303.0,33,590.0,70,ACTIVE,0.84,710.0,0.26,91.0,123.0,41.0,48.0,home

In [81]:
#CO_code_network_coords_product_final["CO_code_num_of_connections_VDSL"] = CO_code_network_coords_product_final["CO_code_num_of_connections_30"] + CO_code_network_coords_product_final["CO_code_num_of_connections_50"] + CO_code_network_coords_product_final["CO_code_num_of_connections_100"] + CO_code_network_coords_product_final["CO_code_num_of_connections_200"]
CO_code_network_coords_product_final["num_of_connections_VDSL"] = CO_code_network_coords_product_final[["num_of_connections_30", "num_of_connections_50", "num_of_connections_100", "num_of_connections_200"]].sum(axis=1, numeric_only = True)

In [82]:
CO_code_network_coords_product_final["speed_ttl_experience"] = CO_code_network_coords_product_final[["mean_Actual_Speed_100", "mean_Actual_Speed_200", "mean_Actual_Speed_30", "mean_Actual_Speed_50", "mean_Actual_Speed_ADSL"]].sum(axis=1, numeric_only = True)

In [83]:
CO_code_network_coords_product_final

,longitude,latitude,Νομός Α/Κ,index,CO_code,mean_Actual_Speed_100,mean_Actual_Speed_200,mean_Actual_Speed_30,mean_Actual_Speed_50,mean_Actual_Speed_ADSL,mean_disconnections_100,mean_disconnections_200,mean_disconnections_30,mean_disconnections_50,mean_disconnections_ADSL,num_of_connections_100,num_of_connections_200,num_of_connections_30,num_of_connections_50,num_of_connections_ADSL,kvID_num,ttl_num_of_connections,CO code,OKSY C,NGA availability,VF base (retail services),VF MS,submitted 12m,created 12m,submitted 6m,created 6m,icon,num_of_connections_VDSL,speed_ttl_experience
0,22.853874,37.244403,ΑΡΚΑΔΙΑΣ,3,16,18.54,NaN,NaN,54.70,NaN,7.0,NaN,NaN,14.0,NaN,1.0,0.0,0.0,1.0,0.0,2,2.0,16,ACTIVE,0.47,2.0,0.00,2.0,2.0,0.0,0.0,home,2.0,73.24
1,22.452459,36.959996,ΛΑΚΩΝΙΑΣ,5,27,39.29,NaN,NaN,49.25,NaN,171.0,NaN,NaN,316.5,NaN,1.0,0.0,0.0,2.0,0.0,1,3.0,27,ACTIVE,0.40,4.0,0.00,1.0,1.0,0.0,0.0,home,3.0,88.54
2,22.078575,37.047754,ΜΕΣΣΗΝΙΑΣ,6,45,107.77,NaN,NaN,48.51,NaN,5.0,NaN,NaN,114.5,NaN,1.0,0.0,0.0,3.0,0.0,2,4.0,45,ACTIVE,0.37,5.0,0.01,10.0,12.0,5.0,6.0,home,4.0,156.28
3,22.111926,37.034498,ΜΕΣΣΗΝΙΑΣ,7,47,90.75,133.71,27.13,51.45,11.46,16.0,77.0,26.7,9.6,31.2,1141.0,15.0,315.0,1562.0,1641.0,196,4674.0,47,ACTIVE,0.74,5275.0,0.21,834.0,988.0,435.0,506.0,home,3033.0,314.50
4,21.941240,37.003638,ΜΕΣΣΗΝΙΑΣ,8,56,NaN,NaN,NaN,27.78,NaN,NaN,NaN,NaN,18.0,NaN,0.0,0.0,0.0,1.0,0.0,1,1.0,56,ACTIVE,0.28,1.0,0.00,NaN,NaN,NaN,NaN,home,1.0,27.78
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
686,24.933898,37.436261,ΚΥΚΛΑΔΩΝ,829,2082,80.17,NaN,NaN,44.79,14.52,14.0,NaN,NaN,14.6,27.4,70.0,0.0,0.0,169.0,213.0,33,452.0,2082,ACTIVE,0.72,497.0,0.17,58.0,69.0,28.0,36.0,home,239.0,139.48
687,22.521566,40.756624,ΠΕΛΛΗΣ,830,2083,NaN,NaN,NaN,NaN,13.45,NaN,NaN,NaN,NaN,6.5,0.0,0.0,0.0,0.0,86.0,6,86.0,2083,Inactive,0.00,288.0,0.47,NaN,NaN,NaN,NaN,home,0.0,13.45
688,28.211207,36.380284,ΔΩΔΕΚΑΝΗΣΟΥ,831,2087,81.18,196.74,NaN,52.08,NaN,40.2,8.0,NaN,9.7,NaN,14.0,1.0,0.0,25.0,0.0,10,40.0,2087,ACTIVE,0.92,54.0,0.05,36.0,46.0,27.0,33.0,home,40.0,330.00
689,21.485059,38.608638,ΑΙΤΩΛΟΑΚΑΡΝΑΝΙΑΣ,832,2091,71.59,52.34,NaN,49.95,15.88,25.5,14.5,NaN,18.1,58.9,51.0,3.0,0.0,113.0,90.0,13,257.0,2091,ACTIVE,0.93,277.0,0.39,30.0,36.0,14.0,17.0,home,167.0,189.76
690,25.037444,35.396333,ΛΥΓΑΡΙΑ,827,2079,NaN,NaN,NaN,55.00,NaN,NaN,NaN,NaN,4.0,NaN,0.0,0.0,0.0,1.0,0.0,1,1.0,2079,ACTIVE,0.42,8.0,0.03,3.0,3.0,2.0,2.0,home,1.0,55.00

In [84]:
CO_code_network_coords_product_final = CO_code_network_coords_product_final.fillna("NO customers")

In [85]:
CO_code_network_coords_product_final.to_csv("CO_code_layer.csv", index = False)

# 2nd Layer

In [86]:
network_kvid_aggs

,CO_code,kvID,DSL,kvID_mean_Actual_Speed,kvID_mean_disconnections,kvID_num_of_connections,Longtitude,Latitude
0,0,0,100,108.04,1.3,3,NaN,NaN
1,0,0,50,46.79,6.1,29,NaN,NaN
2,0,0,ADSL,8.67,17.5,4,NaN,NaN
3,0,101,50,26.84,13.5,4,NaN,NaN
4,0,101,ADSL,14.57,0.0,1,NaN,NaN
...,...,...,...,...,...,...,...,...
76348,995,405,ADSL,17.91,2.0,2,23.705083,40.717083
76349,995,407,50,54.35,32.2,4,23.697417,40.710500
76350,996,113,50,12.61,3.0,1,23.702444,40.664417
76351,996,403,100,107.58,7.0,1,23.691056,40.666583
76352,9996,0,ADSL,21.65,223.0,1,NaN,NaN

In [87]:
network_kvid_aggs["kvID"].nunique()

1085

In [88]:
network_kvid_aggs.dtypes

CO_code                       int64
kvID                          int64
DSL                          object
kvID_mean_Actual_Speed      float64
kvID_mean_disconnections    float64
kvID_num_of_connections       int64
Longtitude                  float64
Latitude                    float64
dtype: object

In [89]:
network_kvid_aggs.count()

CO_code                     76353
kvID                        76353
DSL                         76353
kvID_mean_Actual_Speed      76353
kvID_mean_disconnections    76353
kvID_num_of_connections     76353
Longtitude                  58176
Latitude                    58176
dtype: int64

In [90]:
# check if there are NaN values
network_kvid_aggs.isnull().values.any()
# 1. COUNT how many NaN values we have per each column
for entry in list(network_kvid_aggs.columns.values):
    if network_kvid_aggs[entry].isnull().sum() > 0:
        print(entry, ": ", network_kvid_aggs[entry].isnull().sum())
        # I have to check the proportion (null / total input)
        print("The proportion of null values is: ", ((network_kvid_aggs[entry].isnull().sum() / len(network_kvid_aggs[entry])) * 100, "%"))

True

Longtitude :  18177
The proportion of null values is:  (23.806530195277197, '%')
Latitude :  18177
The proportion of null values is:  (23.806530195277197, '%')

In [91]:
kvid_latlong = network_kvid_aggs[["CO_code", "kvID", "Longtitude", "Latitude"]]

In [92]:
kvid_latlong = kvid_latlong.drop_duplicates(subset=["CO_code", "kvID"])

In [93]:
network_kvid_aggs = network_kvid_aggs[["CO_code", "kvID", "DSL", "kvID_mean_Actual_Speed", "kvID_mean_disconnections", "kvID_num_of_connections"]]

In [94]:
network_kvid_aggs = network_kvid_aggs.set_index(["CO_code", "kvID"])

In [95]:
network_kvid_aggs_pivot = network_kvid_aggs.pivot(columns='DSL')

In [96]:
network_kvid_aggs_pivot

             kvID_mean_Actual_Speed                           \
DSL                             100 200     30     50   ADSL
CO_code kvID
0       0                    108.04 NaN    NaN  46.79   8.67
        70                      NaN NaN    NaN  37.48    NaN
        101                     NaN NaN    NaN  26.84  14.57
        103                    7.95 NaN    NaN   8.19  28.40
        105                     NaN NaN    NaN  41.47  11.41
...                             ...  ..    ...    ...    ...
2269    105                   56.06 NaN    NaN  50.19    NaN
9003    1                       NaN NaN  30.72    NaN    NaN
9004    1                       NaN NaN    NaN  56.32    NaN
9005    1                       NaN NaN  33.77    NaN    NaN
9996    0                       NaN NaN    NaN    NaN  21.65

             kvID_mean_disconnections                        \
DSL                               100 200   30    50   ADSL
CO_code kvID
0       0                         1.3 NaN  NaN   6.1   17.5
        70                        NaN NaN  NaN  11.0    NaN
        101                       NaN NaN  NaN  13.5    0.0
        103                      20.0 NaN  NaN   1.0    8.3
        105                       NaN NaN  NaN  27.8    6.0
...                               ...  ..  ...   ...    ...
2269    105                      39.5 NaN  NaN  46.0    NaN
9003    1                         NaN NaN  1.0   NaN    NaN
9004    1                         NaN NaN  NaN   0.3    NaN
9005    1                         NaN NaN  3.0   NaN    NaN
9996    0                         NaN NaN  NaN   NaN  223.0

             kvID_num_of_connections
DSL                              100 200   30    50 ADSL
CO_code kvID
0       0                        3.0 NaN  NaN  29.0  4.0
        70                       NaN NaN  NaN   1.0  NaN
        101                      NaN NaN  NaN   4.0  1.0
        103                      1.0 NaN  NaN   1.0  3.0
        105                      NaN NaN  NaN   4.0  1.0
...                              ...  ..  ...   ...  ...
2269    105                      2.0 NaN  NaN   2.0  NaN
9003    1                        NaN NaN  1.0   NaN  NaN
9004    1                        NaN NaN  NaN   6.0  NaN
9005    1                        NaN NaN  1.0   NaN  NaN
9996    0                        NaN NaN  NaN   NaN  1.0

[32051 rows x 15 columns]

In [97]:
network_kvid_aggs_pivot.columns = ["_".join((j,k)) for j,k in network_kvid_aggs_pivot.columns]
network_kvid_aggs_pivot.reset_index()

,CO_code,kvID,kvID_mean_Actual_Speed_100,kvID_mean_Actual_Speed_200,kvID_mean_Actual_Speed_30,kvID_mean_Actual_Speed_50,kvID_mean_Actual_Speed_ADSL,kvID_mean_disconnections_100,kvID_mean_disconnections_200,kvID_mean_disconnections_30,kvID_mean_disconnections_50,kvID_mean_disconnections_ADSL,kvID_num_of_connections_100,kvID_num_of_connections_200,kvID_num_of_connections_30,kvID_num_of_connections_50,kvID_num_of_connections_ADSL
0,0,0,108.04,NaN,NaN,46.79,8.67,1.3,NaN,NaN,6.1,17.5,3.0,NaN,NaN,29.0,4.0
1,0,70,NaN,NaN,NaN,37.48,NaN,NaN,NaN,NaN,11.0,NaN,NaN,NaN,NaN,1.0,NaN
2,0,101,NaN,NaN,NaN,26.84,14.57,NaN,NaN,NaN,13.5,0.0,NaN,NaN,NaN,4.0,1.0
3,0,103,7.95,NaN,NaN,8.19,28.40,20.0,NaN,NaN,1.0,8.3,1.0,NaN,NaN,1.0,3.0
4,0,105,NaN,NaN,NaN,41.47,11.41,NaN,NaN,NaN,27.8,6.0,NaN,NaN,NaN,4.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32046,2269,105,56.06,NaN,NaN,50.19,NaN,39.5,NaN,NaN,46.0,NaN,2.0,NaN,NaN,2.0,NaN
32047,9003,1,NaN,NaN,30.72,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,1.0,NaN,NaN
32048,9004,1,NaN,NaN,NaN,56.32,NaN,NaN,NaN,NaN,0.3,NaN,NaN,NaN,NaN,6.0,NaN
32049,9005,1,NaN,NaN,33.77,NaN,NaN,NaN,NaN,3.0,NaN,NaN,NaN,NaN,1.0,NaN,NaN
32050,9996,0,NaN,NaN,NaN,NaN,21.65,NaN,NaN,NaN,NaN,223.0,NaN,NaN,NaN,NaN,1.0

In [98]:
network_kvid_aggs_pivot

              kvID_mean_Actual_Speed_100  kvID_mean_Actual_Speed_200  \
CO_code kvID
0       0                         108.04                         NaN
        70                           NaN                         NaN
        101                          NaN                         NaN
        103                         7.95                         NaN
        105                          NaN                         NaN
...                                  ...                         ...
2269    105                        56.06                         NaN
9003    1                            NaN                         NaN
9004    1                            NaN                         NaN
9005    1                            NaN                         NaN
9996    0                            NaN                         NaN

              kvID_mean_Actual_Speed_30  kvID_mean_Actual_Speed_50  \
CO_code kvID
0       0                           NaN                      46.79
        70                          NaN                      37.48
        101                         NaN                      26.84
        103                         NaN                       8.19
        105                         NaN                      41.47
...                                 ...                        ...
2269    105                         NaN                      50.19
9003    1                         30.72                        NaN
9004    1                           NaN                      56.32
9005    1                         33.77                        NaN
9996    0                           NaN                        NaN

              kvID_mean_Actual_Speed_ADSL  kvID_mean_disconnections_100  \
CO_code kvID
0       0                            8.67                           1.3
        70                            NaN                           NaN
        101                         14.57                           NaN
        103                         28.40                          20.0
        105                         11.41                           NaN
...                                   ...                           ...
2269    105                           NaN                          39.5
9003    1                             NaN                           NaN
9004    1                             NaN                           NaN
9005    1                             NaN                           NaN
9996    0                           21.65                           NaN

              kvID_mean_disconnections_200  kvID_mean_disconnections_30  \
CO_code kvID
0       0                              NaN                          NaN
        70                             NaN                          NaN
        101                            NaN                          NaN
        103                            NaN                          NaN
        105                            NaN                          NaN
...                                    ...                          ...
2269    105                            NaN                          NaN
9003    1                              NaN                          1.0
9004    1                              NaN                          NaN
9005    1                              NaN                          3.0
9996    0                              NaN                          NaN

              kvID_mean_disconnections_50  kvID_mean_disconnections_ADSL  \
CO_code kvID
0       0                             6.1                           17.5
        70                           11.0                            NaN
        101                          13.5                            0.0
        103                           1.0                            8.3
        105                          27.8                            6.0
...                                   ...                            ...
2269    105                          46.0                            NaN
9003    1                             NaN                            NaN
9004    1                             0.3                            NaN
9005    1                             NaN                            NaN
9996    0                             NaN                          223.0

              kvID_num_of_connections_100  kvID_num_of_connections_200  \
CO_code kvID
0       0                             3.0                          NaN
        70                            NaN                          NaN
        101                           NaN                          NaN
        103                           1.0                          NaN
        105                           NaN                          NaN
...                                   ...                          ...
2269    105                           2.0                          NaN
9003    1                             NaN                          NaN
9004    1                             NaN                          NaN
9005    1                             NaN                          NaN
9996    0                             NaN                          NaN

              kvID_num_of_connections_30  kvID_num_of_connections_50  \
CO_code kvID
0       0                            NaN                        29.0
        70                           NaN                         1.0
        101                          NaN                         4.0
        103                          NaN                         1.0
        105                          NaN                         4.0
...                                  ...                         ...
2269    105                          NaN                         2.0
9003    1                            1.0                         NaN
9004    1                            NaN                         6.0
9005    1                            1.0                         NaN
9996    0                            NaN                         NaN

              kvID_num_of_connections_ADSL
CO_code kvID
0       0                              4.0
        70                             NaN
        101                            1.0
        103                            3.0
        105                            1.0
...                                    ...
2269    105                            NaN
9003    1                              NaN
9004    1                              NaN
9005    1                              NaN
9996    0                              1.0

[32051 rows x 15 columns]

In [99]:
network_kvid_aggs_pivot = network_kvid_aggs_pivot.reset_index()
kvid_network_aggs_latlong = network_kvid_aggs_pivot.merge(kvid_latlong, on=["CO_code", "kvID"])

In [100]:
kvid_network_aggs_latlong

,CO_code,kvID,kvID_mean_Actual_Speed_100,kvID_mean_Actual_Speed_200,kvID_mean_Actual_Speed_30,kvID_mean_Actual_Speed_50,kvID_mean_Actual_Speed_ADSL,kvID_mean_disconnections_100,kvID_mean_disconnections_200,kvID_mean_disconnections_30,kvID_mean_disconnections_50,kvID_mean_disconnections_ADSL,kvID_num_of_connections_100,kvID_num_of_connections_200,kvID_num_of_connections_30,kvID_num_of_connections_50,kvID_num_of_connections_ADSL,Longtitude,Latitude
0,0,0,108.04,NaN,NaN,46.79,8.67,1.3,NaN,NaN,6.1,17.5,3.0,NaN,NaN,29.0,4.0,NaN,NaN
1,0,70,NaN,NaN,NaN,37.48,NaN,NaN,NaN,NaN,11.0,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN
2,0,101,NaN,NaN,NaN,26.84,14.57,NaN,NaN,NaN,13.5,0.0,NaN,NaN,NaN,4.0,1.0,NaN,NaN
3,0,103,7.95,NaN,NaN,8.19,28.40,20.0,NaN,NaN,1.0,8.3,1.0,NaN,NaN,1.0,3.0,NaN,NaN
4,0,105,NaN,NaN,NaN,41.47,11.41,NaN,NaN,NaN,27.8,6.0,NaN,NaN,NaN,4.0,1.0,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32046,2269,105,56.06,NaN,NaN,50.19,NaN,39.5,NaN,NaN,46.0,NaN,2.0,NaN,NaN,2.0,NaN,NaN,NaN
32047,9003,1,NaN,NaN,30.72,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN
32048,9004,1,NaN,NaN,NaN,56.32,NaN,NaN,NaN,NaN,0.3,NaN,NaN,NaN,NaN,6.0,NaN,NaN,NaN
32049,9005,1,NaN,NaN,33.77,NaN,NaN,NaN,NaN,3.0,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN
32050,9996,0,NaN,NaN,NaN,NaN,21.65,NaN,NaN,NaN,NaN,223.0,NaN,NaN,NaN,NaN,1.0,NaN,NaN

In [101]:
#kvid_network_aggs_latlong["kvID_num_of_connections_VDSL"] = kvid_network_aggs_latlong["kvID_num_of_connections_30"] + kvid_network_aggs_latlong["kvID_num_of_connections_50"] + kvid_network_aggs_latlong["kvID_num_of_connections_100"] + kvid_network_aggs_latlong["kvID_num_of_connections_200"]
kvid_network_aggs_latlong["kvID_num_of_connections_VDSL"] = kvid_network_aggs_latlong[["kvID_num_of_connections_30", "kvID_num_of_connections_50", "kvID_num_of_connections_100", "kvID_num_of_connections_200"]].sum(axis=1, numeric_only = True)

In [102]:
kvid_network_aggs_latlong[["kvID_mean_Actual_Speed_100", "kvID_mean_Actual_Speed_200", "kvID_mean_Actual_Speed_30", "kvID_mean_Actual_Speed_50", "kvID_mean_Actual_Speed_ADSL",
                                                     "kvID_mean_disconnections_100", "kvID_mean_disconnections_200", "kvID_mean_disconnections_30", "kvID_mean_disconnections_50", "kvID_mean_disconnections_ADSL",
                                                     "kvID_num_of_connections_100", "kvID_num_of_connections_200", "kvID_num_of_connections_30", "kvID_num_of_connections_50", "kvID_num_of_connections_ADSL"]] = kvid_network_aggs_latlong[["kvID_mean_Actual_Speed_100", "kvID_mean_Actual_Speed_200", "kvID_mean_Actual_Speed_30", "kvID_mean_Actual_Speed_50", "kvID_mean_Actual_Speed_ADSL",
                                                     "kvID_mean_disconnections_100", "kvID_mean_disconnections_200", "kvID_mean_disconnections_30", "kvID_mean_disconnections_50", "kvID_mean_disconnections_ADSL",
                                                     "kvID_num_of_connections_100", "kvID_num_of_connections_200", "kvID_num_of_connections_30", "kvID_num_of_connections_50", "kvID_num_of_connections_ADSL"]].fillna("NO customers")

In [103]:
kvid_network_aggs_latlong

,CO_code,kvID,kvID_mean_Actual_Speed_100,kvID_mean_Actual_Speed_200,kvID_mean_Actual_Speed_30,kvID_mean_Actual_Speed_50,kvID_mean_Actual_Speed_ADSL,kvID_mean_disconnections_100,kvID_mean_disconnections_200,kvID_mean_disconnections_30,kvID_mean_disconnections_50,kvID_mean_disconnections_ADSL,kvID_num_of_connections_100,kvID_num_of_connections_200,kvID_num_of_connections_30,kvID_num_of_connections_50,kvID_num_of_connections_ADSL,Longtitude,Latitude,kvID_num_of_connections_VDSL
0,0,0,108.04,NO customers,NO customers,46.79,8.67,1.3,NO customers,NO customers,6.1,17.5,3,NO customers,NO customers,29,4,NaN,NaN,32.0
1,0,70,NO customers,NO customers,NO customers,37.48,NO customers,NO customers,NO customers,NO customers,11,NO customers,NO customers,NO customers,NO customers,1,NO customers,NaN,NaN,1.0
2,0,101,NO customers,NO customers,NO customers,26.84,14.57,NO customers,NO customers,NO customers,13.5,0,NO customers,NO customers,NO customers,4,1,NaN,NaN,4.0
3,0,103,7.95,NO customers,NO customers,8.19,28.4,20,NO customers,NO customers,1,8.3,1,NO customers,NO customers,1,3,NaN,NaN,2.0
4,0,105,NO customers,NO customers,NO customers,41.47,11.41,NO customers,NO customers,NO customers,27.8,6,NO customers,NO customers,NO customers,4,1,NaN,NaN,4.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32046,2269,105,56.06,NO customers,NO customers,50.19,NO customers,39.5,NO customers,NO customers,46,NO customers,2,NO customers,NO customers,2,NO customers,NaN,NaN,4.0
32047,9003,1,NO customers,NO customers,30.72,NO customers,NO customers,NO customers,NO customers,1,NO customers,NO customers,NO customers,NO customers,1,NO customers,NO customers,NaN,NaN,1.0
32048,9004,1,NO customers,NO customers,NO customers,56.32,NO customers,NO customers,NO customers,NO customers,0.3,NO customers,NO customers,NO customers,NO customers,6,NO customers,NaN,NaN,6.0
32049,9005,1,NO customers,NO customers,33.77,NO customers,NO customers,NO customers,NO customers,3,NO customers,NO customers,NO customers,NO customers,1,NO customers,NO customers,NaN,NaN,1.0
32050,9996,0,NO customers,NO customers,NO customers,NO customers,21.65,NO customers,NO customers,NO customers,NO customers,223,NO customers,NO customers,NO customers,NO customers,1,NaN,NaN,0.0

In [104]:
kvid_network_aggs_latlong = kvid_network_aggs_latlong.rename(columns={"Longtitude": "longitude", "Latitude": "latitude"})

In [105]:
kvid_network_aggs_latlong = kvid_network_aggs_latlong.rename(columns={"kvID_mean_Actual_Speed_100": "mean_Actual_Speed_100",
                                                                      "kvID_mean_Actual_Speed_200": "mean_Actual_Speed_200",
                                                                      "kvID_mean_Actual_Speed_30": "mean_Actual_Speed_30",
                                                                      "kvID_mean_Actual_Speed_50": "mean_Actual_Speed_50",
                                                                      "kvID_mean_Actual_Speed_ADSL": "mean_Actual_Speed_ADSL",
                                                                      "kvID_mean_disconnections_100": "mean_disconnections_100",
                                                                      "kvID_mean_disconnections_200": "mean_disconnections_200",
                                                                      "kvID_mean_disconnections_30": "mean_disconnections_30",
                                                                      "kvID_mean_disconnections_50": "mean_disconnections_50",
                                                                      "kvID_mean_disconnections_ADSL": "mean_disconnections_ADSL",
                                                                      "kvID_num_of_connections_100": "num_of_connections_100",
                                                                      "kvID_num_of_connections_200": "num_of_connections_200",
                                                                      "kvID_num_of_connections_30": "num_of_connections_30",
                                                                      "kvID_num_of_connections_50": "num_of_connections_50",
                                                                      "kvID_num_of_connections_ADSL": "num_of_connections_ADSL",
                                                                      "kvID_num_of_connections_VDSL": "num_of_connections_VDSL"
                                                                      })

In [106]:
kvid_network_aggs_latlong["icon"] = 'place'

In [107]:
#kvid_network_aggs_latlong

In [108]:
kvid_network_aggs_latlong.shape

(32051, 21)

In [109]:
kvid_network_aggs_latlong = kvid_network_aggs_latlong[~((kvid_network_aggs_latlong["CO_code"] == 444) & (kvid_network_aggs_latlong["kvID"] == 539))]

In [110]:
kvid_network_aggs_latlong[(kvid_network_aggs_latlong["CO_code"] == 444) & (kvid_network_aggs_latlong["kvID"] == 539)]

Empty DataFrame
Columns: [CO_code, kvID, mean_Actual_Speed_100, mean_Actual_Speed_200, mean_Actual_Speed_30, mean_Actual_Speed_50, mean_Actual_Speed_ADSL, mean_disconnections_10, mean_disconnections_200, mean_disconnections_30, mean_disconnections_50, mean_disconnections_ADSL, num_of_connections_100, num_of_connections_200, num_of_connections_30, num_of_connections_50, num_of_connections_ADSL, longitude, latitude, num_of_connections_VDSL, icon]
Index: []

In [111]:
kvid_network_aggs_latlong_final = kvid_network_aggs_latlong[~kvid_network_aggs_latlong["longitude"].isnull()]

In [112]:
kvid_network_aggs_latlong_final.shape

(20156, 21)

In [113]:
#kvid_network_aggs_latlong_final = kvid_network_aggs_latlong_final.fillna("NO customers")

In [114]:
kvid_network_aggs_latlong_final[(kvid_network_aggs_latlong_final["CO_code"] == 444) & (kvid_network_aggs_latlong_final["kvID"] == 539)]

kvid_network_aggs_latlong_final[(kvid_network_aggs_latlong_final["CO_code"] == 1398) & (kvid_network_aggs_latlong_final["kvID"] == 111)]

Empty DataFrame
Columns: [CO_code, kvID, mean_Actual_Speed_100, mean_Actual_Speed_200, mean_Actual_Speed_30, mean_Actual_Speed_50, mean_Actual_Speed_ADSL, mean_disconnections_10, mean_disconnections_200, mean_disconnections_30, mean_disconnections_50, mean_disconnections_ADSL, num_of_connections_100, num_of_connections_200, num_of_connections_30, num_of_connections_50, num_of_connections_ADSL, longitude, latitude, num_of_connections_VDSL, icon]
Index: []

,CO_code,kvID,mean_Actual_Speed_100,mean_Actual_Speed_200,mean_Actual_Speed_30,mean_Actual_Speed_50,mean_Actual_Speed_ADSL,mean_disconnections_10,mean_disconnections_200,mean_disconnections_30,mean_disconnections_50,mean_disconnections_ADSL,num_of_connections_100,num_of_connections_200,num_of_connections_30,num_of_connections_50,num_of_connections_ADSL,longitude,latitude,num_of_connections_VDSL,icon
22613,1398,111,NO customers,NO customers,26.65,49.61,14.8,NO customers,NO customers,21.5,17.6,77.7,NO customers,NO customers,2,5,15,25.121361,35.336417,7.0,place

In [115]:
#kvid_network_aggs_latlong_final = kvid_network_aggs_latlong_final[~((kvid_network_aggs_latlong_final["CO_code"] == 444) & (kvid_network_aggs_latlong_final["kvID"] == 539))]

In [116]:
kvid_network_aggs_latlong_final.to_csv("kvID_layer.csv", index = False)

In [117]:
kvid_network_aggs_latlong_final[(kvid_network_aggs_latlong_final["CO_code"] == 444) & (kvid_network_aggs_latlong_final["kvID"] == 539)]

kvid_network_aggs_latlong_final[(kvid_network_aggs_latlong_final["CO_code"] == 1398) & (kvid_network_aggs_latlong_final["kvID"] == 111)]

Empty DataFrame
Columns: [CO_code, kvID, mean_Actual_Speed_100, mean_Actual_Speed_200, mean_Actual_Speed_30, mean_Actual_Speed_50, mean_Actual_Speed_ADSL, mean_disconnections_10, mean_disconnections_200, mean_disconnections_30, mean_disconnections_50, mean_disconnections_ADSL, num_of_connections_100, num_of_connections_200, num_of_connections_30, num_of_connections_50, num_of_connections_ADSL, longitude, latitude, num_of_connections_VDSL, icon]
Index: []

,CO_code,kvID,mean_Actual_Speed_100,mean_Actual_Speed_200,mean_Actual_Speed_30,mean_Actual_Speed_50,mean_Actual_Speed_ADSL,mean_disconnections_10,mean_disconnections_200,mean_disconnections_30,mean_disconnections_50,mean_disconnections_ADSL,num_of_connections_100,num_of_connections_200,num_of_connections_30,num_of_connections_50,num_of_connections_ADSL,longitude,latitude,num_of_connections_VDSL,icon
22613,1398,111,NO customers,NO customers,26.65,49.61,14.8,NO customers,NO customers,21.5,17.6,77.7,NO customers,NO customers,2,5,15,25.121361,35.336417,7.0,place

# 3rd Layer

In [118]:
CO_code_network_coords_product.head()

,longitude,latitude,Νομός Α/Κ,index,CO_code,mean_Actual_Speed_100,mean_Actual_Speed_200,mean_Actual_Speed_30,mean_Actual_Speed_50,mean_Actual_Speed_ADSL,mean_disconnections_100,mean_disconnections_200,mean_disconnections_30,mean_disconnections_50,mean_disconnections_ADSL,num_of_connections_100,num_of_connections_200,num_of_connections_30,num_of_connections_50,num_of_connections_ADSL,kvID_num,ttl_num_of_connections,CO code,OKSY C,NGA availability,VF base (retail services),VF MS,submitted 12m,created 12m,submitted 6m,created 6m,icon,num_of_connections_VDSL,speed_ttl_experience
0,22.853874,37.244403,ΑΡΚΑΔΙΑΣ,3,16,18.54,NaN,NaN,54.70,NaN,7.0,NaN,NaN,14.0,NaN,1.0,0.0,0.0,1.0,0.0,2,2.0,16,ACTIVE,0.47,2.0,0.00,2.0,2.0,0.0,0.0,home,2.0,73.24
1,22.452459,36.959996,ΛΑΚΩΝΙΑΣ,5,27,39.29,NaN,NaN,49.25,NaN,171.0,NaN,NaN,316.5,NaN,1.0,0.0,0.0,2.0,0.0,1,3.0,27,ACTIVE,0.40,4.0,0.00,1.0,1.0,0.0,0.0,home,3.0,88.54
2,22.078575,37.047754,ΜΕΣΣΗΝΙΑΣ,6,45,107.77,NaN,NaN,48.51,NaN,5.0,NaN,NaN,114.5,NaN,1.0,0.0,0.0,3.0,0.0,2,4.0,45,ACTIVE,0.37,5.0,0.01,10.0,12.0,5.0,6.0,home,4.0,156.28
3,22.111926,37.034498,ΜΕΣΣΗΝΙΑΣ,7,47,90.75,133.71,27.13,51.45,11.46,16.0,77.0,26.7,9.6,31.2,1141.0,15.0,315.0,1562.0,1641.0,196,4674.0,47,ACTIVE,0.74,5275.0,0.21,834.0,988.0,435.0,506.0,home,3033.0,314.50
4,21.941240,37.003638,ΜΕΣΣΗΝΙΑΣ,8,56,NaN,NaN,NaN,27.78,NaN,NaN,NaN,NaN,18.0,NaN,0.0,0.0,0.0,1.0,0.0,1,1.0,56,ACTIVE,0.28,1.0,0.00,NaN,NaN,NaN,NaN,home,1.0,27.78

In [119]:
from shapely import wkt
import geopandas as gpd

geo_gr = pd.read_csv('C:/Users/zagkoui/OneDrive - Vodafone Group/Documents/FIXED_VISUALIZATION/home_lac_ENUTS3.csv')

geo_gr['geometry'] = geo_gr['geometry'].apply(wkt.loads)
geo_gr = gpd.GeoDataFrame(geo_gr, crs='epsg:4326')

geo_gr = geo_gr[geo_gr.CNTRY_NAME == 'Greece']

In [120]:
geo_gr

,CNTRY_NAME,CNTRY_CODE,BPL_CODE,ENUTS3,ADMIN_NAME,geometry,d
0,Greece,300,43060.0,12111,Evros,"MULTIPOLYGON (((25.82747 40.47122, 25.82583 40...",EL111
1,Greece,300,43060.0,12112,Xanthi,"MULTIPOLYGON (((25.14167 40.99015, 25.14099 40...",EL112
2,Greece,300,43060.0,12113,Rodopi,"MULTIPOLYGON (((25.62294 40.86081, 25.62161 40...",EL113
3,Greece,300,43060.0,12114,Drama,"POLYGON ((24.29037 41.55131, 24.29556 41.54730...",EL114
4,Greece,300,43060.0,12115,Kavala,"MULTIPOLYGON (((24.63083 40.55455, 24.62831 40...",EL115
5,Greece,300,43060.0,12121,Imathia,"POLYGON ((22.06954 40.73171, 22.06996 40.73162...",EL121
6,Greece,300,43060.0,12122,Thessaloniki,"MULTIPOLYGON (((22.74783 40.51747, 22.74747 40...",EL122
7,Greece,300,43060.0,12123,Kilkis,"POLYGON ((22.81576 41.33908, 22.82273 41.33420...",EL123
8,Greece,300,43060.0,12124,Pella,"POLYGON ((22.23009 41.16500, 22.23590 41.16338...",EL124
9,Greece,300,43060.0,12125,Pieria,"POLYGON ((22.53282 40.54157, 22.53413 40.54125...",EL125
10,Greece,300,43060.0,12126,Serres,"POLYGON ((23.53556 41.40153, 23.53539 41.39876...",EL126
11,Greece,300,43060.0,12127,Chalkidiki,"MULTIPOLYGON (((23.35711 39.95831, 23.35664 39...",EL127
12,Greece,300,43060.0,12131,Grevena,"POLYGON ((21.86039 39.95614, 21.86076 39.95534...",EL131
13,Greece,300,43060.0,12132,Kastoria,"POLYGON ((21.28508 40.70783, 21.28492 40.70774...",EL132
14,Greece,300,43060.0,12133,Kozani,"POLYGON ((21.84400 40.70565, 21.84410 40.70565...",EL133
15,Greece,300,43060.0,12134,Florina,"POLYGON ((21.75366 40.92679, 21.76202 40.92632...",EL134
16,Greece,300,43060.0,12141,Karditsa,"POLYGON ((22.09356 39.55280, 22.09387 39.55279...",EL141
17,Greece,300,43060.0,12142,Larisa,"POLYGON ((22.18427 40.19327, 22.18556 40.19296...",EL142
18,Greece,300,43060.0,12143,Magnisia,"MULTIPOLYGON (((23.06330 39.01120, 23.06744 39...",EL143
19,Greece,300,43060.0,12144,Trikala,"POLYGON ((21.47350 39.89756, 21.47456 39.89700...",EL144
20,Greece,300,43060.0,12211,Arta,"MULTIPOLYGON (((20.92753 38.98539, 20.92664 38...",EL211
21,Greece,300,43060.0,12212,Thesprotia,"MULTIPOLYGON (((20.27367 39.37075, 20.27236 39...",EL212
22,Greece,300,43060.0,12213,Ioannina,"POLYGON ((20.86683 40.37412, 20.86748 40.37287...",EL213
23,Greece,300,43060.0,12214,Preveza,"MULTIPOLYGON (((20.83917 38.96206, 20.83747 38...",EL214
24,Greece,300,43060.0,12221,Zakynthos,"MULTIPOLYGON (((21.01331 37.24792, 21.01167 37...",EL221
25,Greece,300,43060.0,12222,Kerkyra,"MULTIPOLYGON (((20.26653 39.11539, 20.26572 39...",EL222
26,Greece,300,43060.0,12223,Kefallinia,"MULTIPOLYGON (((20.54544 38.08664, 20.54503 38...",EL223
27,Greece,300,43060.0,12224,Lefkada,"MULTIPOLYGON (((20.88497 38.54456, 20.88411 38...",EL224
28,Greece,300,43060.0,12231,Aitoloakarnania,"MULTIPOLYGON (((21.51083 38.29036, 21.50917 38...",EL231
29,Greece,300,43060.0,12232,Achaia,"MULTIPOLYGON (((21.38544 38.21083, 21.38414 38...",EL232
30,Greece,300,43060.0,12233,Ilia,"MULTIPOLYGON (((21.30208 37.66164, 21.30208 37...",EL233
31,Greece,300,43060.0,12241,Voiotia,"MULTIPOLYGON (((22.96994 38.18042, 22.97122 38...",EL241
32,Greece,300,43060.0,12242,Evvoia,"MULTIPOLYGON (((24.52708 37.93500, 24.52744 37...",EL242
33,Greece,300,43060.0,12243,Evrytania,"POLYGON ((21.93685 39.06246, 21.93575 39.06200...",EL243
34,Greece,300,43060.0,12244,Fthiotida,"MULTIPOLYGON (((23.30120 38.57750, 23.30083 38...",EL244
35,Greece,300,43060.0,12245,Fokida,"MULTIPOLYGON (((22.62414 38.31372, 22.62583 38...",EL245
36,Greece,300,43060.0,12251,Argolida,"MULTIPOLYGON (((23.14225 37.30043, 23.14081 37...",EL251
37,Greece,300,43060.0,12252,Arkadia,"MULTIPOLYGON (((22.84667 37.30125, 22.84581 37...",EL252
38,Greece,300,43060.0,12253,Korinthia,"MULTIPOLYGON (((23.15828 37.75544, 23.15747 37...",EL253
39,Greece,300,43060.0,12254,Lakonia,"MULTIPOLYGON (((22.41245 36.41872, 22.41083 36...",EL254
40,Greece,300,43060.0,12255,Messinia,"MULTIPOLYGON (((21.89581 36.67205, 21.89497 36...",EL255
41,Greece,300,43060.0,12300,Attiki,"MULTIPOLYGON (((23.30586 35.89039, 23.30417 35...",EL300
42,Greece,300,43060.0,12411,Lesvos,"MULTIPOLYGON (((26.51247 38.96289, 26.51161 38...",EL411
43,Greece,300,43060.0,12412,Samos,"MULTIPOLYGON (((26.49528 37.50289, 26.49250 37...",EL412
44,Greece,300,43060.0,12413,Chios,"MULTIPOLYGON (((26.01708 38.12417, 26.01664 38...",EL413
45,Greece,300,43060.0,12421,Dodekanisos,"MULTIPOLYGON (((26.86245 35.34455, 26.86167 35...",EL421
46,Greece,300,43060.0,12422,Kyklades,"MULTIPOLYGON (((25.23333 36.21958, 25.23247 36...",EL422
47,Greece,300,43060.0,12431,Iraklio,"MULTIPOLYGON (((24.80208 34.92164, 24.80161 34...",EL431
48,Greece,300,43060.0,12432,Lasithi,"MULTIPOLYGON (((25.74403 34.87479, 25.74331 34...",EL432
49,Greece,300,43060.0,12433,Rethymni,"MULTIPOLYGON (((24.59360 35.00646, 24.59153 35...",EL433
50,Greece,300,43060.0,12434,Chania,"MULTIPOLYGON (((24.11539 34.86417, 24.11497 34...",EL434

In [121]:
# Create a geopandas dataframe with cabins
import geopandas as gpd
geo_pc = gpd.GeoDataFrame(CO_code_network_coords_product, geometry=gpd.points_from_xy(CO_code_network_coords_product.longitude, CO_code_network_coords_product.latitude))

In [122]:
geo_pc.head(10)

,longitude,latitude,Νομός Α/Κ,index,CO_code,mean_Actual_Speed_100,mean_Actual_Speed_200,mean_Actual_Speed_30,mean_Actual_Speed_50,mean_Actual_Speed_ADSL,mean_disconnections_100,mean_disconnections_200,mean_disconnections_30,mean_disconnections_50,mean_disconnections_ADSL,num_of_connections_100,num_of_connections_200,num_of_connections_30,num_of_connections_50,num_of_connections_ADSL,kvID_num,ttl_num_of_connections,CO code,OKSY C,NGA availability,VF base (retail services),VF MS,submitted 12m,created 12m,submitted 6m,created 6m,icon,num_of_connections_VDSL,speed_ttl_experience,geometry
0,22.853874,37.244403,ΑΡΚΑΔΙΑΣ,3,16,18.54,NaN,NaN,54.70,NaN,7.0,NaN,NaN,14.0,NaN,1.0,0.0,0.0,1.0,0.0,2,2.0,16,ACTIVE,0.47,2.0,0.00,2.0,2.0,0.0,0.0,home,2.0,73.24,POINT (22.85387 37.24440)
1,22.452459,36.959996,ΛΑΚΩΝΙΑΣ,5,27,39.29,NaN,NaN,49.25,NaN,171.0,NaN,NaN,316.5,NaN,1.0,0.0,0.0,2.0,0.0,1,3.0,27,ACTIVE,0.40,4.0,0.00,1.0,1.0,0.0,0.0,home,3.0,88.54,POINT (22.45246 36.96000)
2,22.078575,37.047754,ΜΕΣΣΗΝΙΑΣ,6,45,107.77,NaN,NaN,48.51,NaN,5.0,NaN,NaN,114.5,NaN,1.0,0.0,0.0,3.0,0.0,2,4.0,45,ACTIVE,0.37,5.0,0.01,10.0,12.0,5.0,6.0,home,4.0,156.28,POINT (22.07857 37.04775)
3,22.111926,37.034498,ΜΕΣΣΗΝΙΑΣ,7,47,90.75,133.71,27.13,51.45,11.46,16.0,77.0,26.7,9.6,31.2,1141.0,15.0,315.0,1562.0,1641.0,196,4674.0,47,ACTIVE,0.74,5275.0,0.21,834.0,988.0,435.0,506.0,home,3033.0,314.50,POINT (22.11193 37.03450)
4,21.941240,37.003638,ΜΕΣΣΗΝΙΑΣ,8,56,NaN,NaN,NaN,27.78,NaN,NaN,NaN,NaN,18.0,NaN,0.0,0.0,0.0,1.0,0.0,1,1.0,56,ACTIVE,0.28,1.0,0.00,NaN,NaN,NaN,NaN,home,1.0,27.78,POINT (21.94124 37.00364)
5,21.929222,36.957189,ΜΕΣΣΗΝΙΑΣ,9,59,49.32,NaN,NaN,47.54,12.84,19.1,NaN,NaN,11.1,44.0,6.0,0.0,0.0,14.0,108.0,10,128.0,59,ACTIVE,0.22,161.0,0.23,7.0,11.0,4.0,5.0,home,20.0,109.70,POINT (21.92922 36.95719)
6,21.695455,36.912130,ΜΕΣΣΗΝΙΑΣ,11,62,59.60,NaN,NaN,53.41,16.13,8.4,NaN,NaN,47.0,26.8,6.0,0.0,0.0,8.0,264.0,16,278.0,62,ACTIVE,0.23,351.0,0.26,26.0,38.0,18.0,24.0,home,14.0,129.14,POINT (21.69545 36.91213)
7,22.882110,37.906294,ΚΟΡΙΝΘΙΑΣ,14,68,31.59,NaN,NaN,48.83,11.42,12.3,NaN,NaN,40.4,23.8,14.0,0.0,0.0,14.0,114.0,10,142.0,68,ACTIVE,0.30,194.0,0.26,20.0,26.0,10.0,15.0,home,28.0,91.84,POINT (22.88211 37.90629)
8,22.930735,37.938625,ΚΟΡΙΝΘΙΑΣ,15,69,85.10,NaN,30.84,48.58,13.24,25.3,NaN,8.1,21.5,22.8,505.0,0.0,27.0,1025.0,1091.0,130,2648.0,69,ACTIVE,0.73,3092.0,0.24,440.0,604.0,248.0,301.0,home,1557.0,177.76,POINT (22.93073 37.93863)
9,22.840894,37.937308,ΚΟΡΙΝΘΙΑΣ,16,70,69.60,104.33,NaN,44.56,10.70,13.0,15.8,NaN,20.0,27.2,82.0,4.0,0.0,201.0,303.0,33,590.0,70,ACTIVE,0.84,710.0,0.26,91.0,123.0,41.0,48.0,home,287.0,229.19,POINT (22.84089 37.93731)

In [123]:
import rtree
# oxi left ---- INNER
co_code_gr_area_data = gpd.sjoin(geo_gr, geo_pc)

In [124]:
co_code_gr_area_data.head(10)

,CNTRY_NAME,CNTRY_CODE,BPL_CODE,ENUTS3,ADMIN_NAME,geometry,d,index_right,longitude,latitude,Νομός Α/Κ,index,CO_code,mean_Actual_Speed_100,mean_Actual_Speed_200,mean_Actual_Speed_30,mean_Actual_Speed_50,mean_Actual_Speed_ADSL,mean_disconnections_100,mean_disconnections_200,mean_disconnections_30,mean_disconnections_50,mean_disconnections_ADSL,num_of_connections_100,num_of_connections_200,num_of_connections_30,num_of_connections_50,num_of_connections_ADSL,kvID_num,ttl_num_of_connections,CO code,OKSY C,NGA availability,VF base (retail services),VF MS,submitted 12m,created 12m,submitted 6m,created 6m,icon,num_of_connections_VDSL,speed_ttl_experience
0,Greece,300,43060.0,12111,Evros,"MULTIPOLYGON (((25.82747 40.47122, 25.82583 40...",EL111,131,25.873993,40.845420,ΕΒΡΟΥ,161,417,92.42,159.07,26.90,51.51,14.08,8.3,15.0,8.5,9.0,11.2,1141.0,63.0,8.0,1905.0,1075.0,142,4192.0,417,ACTIVE,1.00,4639.0,0.23,759.0,916.0,346.0,420.0,home,3117.0,343.98
0,Greece,300,43060.0,12111,Evros,"MULTIPOLYGON (((25.82747 40.47122, 25.82583 40...",EL111,616,25.834690,40.847582,ΕΒΡΟΥ,736,1782,81.86,93.32,NaN,39.04,10.52,16.5,19.1,NaN,27.3,9.0,33.0,5.0,0.0,75.0,182.0,11,295.0,1782,ACTIVE,0.56,314.0,0.24,48.0,54.0,16.0,21.0,home,113.0,224.74
0,Greece,300,43060.0,12111,Evros,"MULTIPOLYGON (((25.82747 40.47122, 25.82583 40...",EL111,493,26.171822,40.894498,ΕΒΡΟΥ,589,1446,102.80,NaN,NaN,47.88,NaN,5.5,NaN,NaN,7.9,NaN,2.0,0.0,0.0,6.0,0.0,4,8.0,1446,ACTIVE,0.46,23.0,0.01,13.0,15.0,5.0,7.0,home,8.0,150.68
0,Greece,300,43060.0,12111,Evros,"MULTIPOLYGON (((25.82747 40.47122, 25.82583 40...",EL111,133,26.303783,41.192262,ΕΒΡΟΥ,164,435,NaN,NaN,NaN,43.94,NaN,NaN,NaN,NaN,22.0,NaN,0.0,0.0,0.0,2.0,0.0,2,2.0,435,ACTIVE,0.18,2.0,0.00,2.0,5.0,0.0,0.0,home,2.0,43.94
0,Greece,300,43060.0,12111,Evros,"MULTIPOLYGON (((25.82747 40.47122, 25.82583 40...",EL111,395,26.493696,41.348682,ΕΒΡΟΥ,467,1167,84.45,NaN,NaN,51.55,13.58,9.9,NaN,NaN,17.7,31.2,69.0,0.0,0.0,109.0,217.0,38,395.0,1167,ACTIVE,0.58,419.0,0.13,96.0,111.0,39.0,46.0,home,178.0,149.58
0,Greece,300,43060.0,12111,Evros,"MULTIPOLYGON (((25.82747 40.47122, 25.82583 40...",EL111,132,26.531983,41.501716,ΕΒΡΟΥ,163,424,91.58,72.56,32.43,51.92,14.85,21.2,4.0,30.8,19.0,15.7,170.0,1.0,78.0,237.0,250.0,61,736.0,424,ACTIVE,0.77,818.0,0.11,191.0,230.0,96.0,118.0,home,486.0,263.34
1,Greece,300,43060.0,12112,Xanthi,"MULTIPOLYGON (((25.14167 40.99015, 25.14099 40...",EL112,486,24.833650,40.928779,ΞΑΝΘΗΣ,581,1430,71.74,NaN,NaN,46.47,NaN,91.4,NaN,NaN,69.5,NaN,5.0,0.0,0.0,2.0,0.0,2,7.0,1430,ACTIVE,0.46,8.0,0.02,4.0,5.0,1.0,2.0,home,7.0,118.21
1,Greece,300,43060.0,12112,Xanthi,"MULTIPOLYGON (((25.14167 40.99015, 25.14099 40...",EL112,128,24.796006,40.985358,ΞΑΝΘΗΣ,158,413,77.84,NaN,NaN,48.21,NaN,17.5,NaN,NaN,45.0,NaN,2.0,0.0,0.0,4.0,0.0,5,6.0,413,ACTIVE,0.53,9.0,0.01,9.0,13.0,5.0,7.0,home,6.0,126.05
1,Greece,300,43060.0,12112,Xanthi,"MULTIPOLYGON (((25.14167 40.99015, 25.14099 40...",EL112,615,24.962071,41.060521,ΞΑΝΘΗΣ,735,1777,NaN,NaN,NaN,28.90,NaN,NaN,NaN,NaN,90.8,NaN,0.0,0.0,0.0,3.0,0.0,2,3.0,1777,ACTIVE,0.28,4.0,0.01,5.0,4.0,1.0,1.0,home,3.0,28.90
1,Greece,300,43060.0,12112,Xanthi,"MULTIPOLYGON (((25.14167 40.99015, 25.14099 40...",EL112,484,24.797300,41.077334,ΞΑΝΘΗΣ,579,1427,NaN,NaN,NaN,45.43,NaN,NaN,NaN,NaN,4.0,NaN,0.0,0.0,0.0,2.0,0.0,1,2.0,1427,ACTIVE,0.40,5.0,0.01,6.0,9.0,5.0,6.0,home,2.0,45.43

In [125]:
geometry = co_code_gr_area_data[["ADMIN_NAME", "geometry"]]
geometry = geometry.drop_duplicates()

In [126]:
nomos_co_code_num = co_code_gr_area_data.groupby("ADMIN_NAME")["CO_code"].nunique().reset_index().rename(columns={"CO_code":"CO_code_num"})
#nomos_co_code_num = co_code_gr_area_data.groupby(["ADMIN_NAME"]).agg({'CO_code':'count'}).rename(columns={"CO_code":"CO_code_num"})

In [127]:
nomos_co_code_num

         ADMIN_NAME  CO_code_num
0            Achaia           20
1   Aitoloakarnania           24
2          Argolida            6
3           Arkadia            3
4              Arta            8
5            Attiki          111
6        Chalkidiki            2
7            Chania           13
8             Chios            2
9       Dodekanisos           14
10            Drama            6
11            Evros            6
12        Evrytania            1
13           Evvoia           17
14          Florina           14
15           Fokida            6
16        Fthiotida           21
17          Grevena            6
18             Ilia           10
19          Imathia           26
20         Ioannina           10
21          Iraklio           41
22         Karditsa            9
23         Kastoria           14
24           Kavala           15
25       Kefallinia            1
26          Kerkyra            4
27           Kilkis            8
28        Korinthia           15
29           Kozani           28
30         Kyklades           12
31          Lakonia            4
32           Larisa           22
33          Lasithi           15
34          Lefkada            1
35           Lesvos            5
36         Magnisia           12
37         Messinia           12
38            Pella           31
39           Pieria           10
40          Preveza            8
41         Rethymni            6
42           Rodopi            6
43            Samos            1
44           Serres            9
45       Thesprotia            3
46     Thessaloniki           50
47          Trikala            4
48          Voiotia            8
49           Xanthi            8
50        Zakynthos            2

In [128]:
co_code_gr_area_data.dtypes

CNTRY_NAME                     object
CNTRY_CODE                      int64
BPL_CODE                      float64
ENUTS3                          int64
ADMIN_NAME                     object
geometry                     geometry
d                              object
index_right                     int64
longitude                     float64
latitude                      float64
Νομός Α/Κ                      object
index                           int64
CO_code                         int64
mean_Actual_Speed_100         float64
mean_Actual_Speed_200         float64
mean_Actual_Speed_30          float64
mean_Actual_Speed_50          float64
mean_Actual_Speed_ADSL        float64
mean_disconnections_100       float64
mean_disconnections_200       float64
mean_disconnections_30        float64
mean_disconnections_50        float64
mean_disconnections_ADSL      float64
num_of_connections_100        float64
num_of_connections_200        float64
num_of_connections_30         float64
num_of_connections_50         float64
num_of_connections_ADSL       float64
kvID_num                        int64
ttl_num_of_connections        float64
CO code                         int64
OKSY C                         object
NGA availability              float64
VF base (retail services)     float64
VF MS                         float64
submitted 12m                 float64
created 12m                   float64
submitted 6m                  float64
created 6m                    float64
icon                           object
num_of_connections_VDSL       float64
speed_ttl_experience          float64
dtype: object

In [129]:
admin_aggs = co_code_gr_area_data.groupby(["ADMIN_NAME"]).agg({'mean_Actual_Speed_100':'mean', 'mean_Actual_Speed_200':'mean', 'mean_Actual_Speed_30':'mean', 'mean_Actual_Speed_50':'mean', 'mean_Actual_Speed_ADSL':'mean', 
                                                              'mean_disconnections_100':'mean', 'mean_disconnections_200':'mean','mean_disconnections_30':'mean', 'mean_disconnections_50':'mean', 'mean_disconnections_ADSL':'mean', 
                                                              'num_of_connections_100':'sum', 'num_of_connections_200':'sum','num_of_connections_30':'sum', 'num_of_connections_50':'sum', 'num_of_connections_ADSL':'sum',
                                                              'VF MS': 'mean', 'NGA availability':'mean','kvID_num': 'sum', 'ttl_num_of_connections': 'sum',
                                                             'VF base (retail services)' : 'sum'}).rename(columns= {'mean_Actual_Speed_200':'mean_Actual_Speed_200', 'mean_Actual_Speed_100':'mean_Actual_Speed_100', 'mean_Actual_Speed_30':'mean_Actual_Speed_30', 'mean_Actual_Speed_50':'mean_Actual_Speed_50', 'mean_Actual_Speed_ADSL':'mean_Actual_Speed_ADSL',
                                                                                                                   'mean_disconnections_200':'mean_disconnections_200','mean_disconnections_100':'mean_disconnections_100', 'mean_disconnections_30':'mean_disconnections_30', 'mean_disconnections_50':'mean_disconnections_50', 'mean_disconnections_ADSL':'mean_disconnections_ADSL',
                                                                                                                   'num_of_connections_100':'num_of_connections_100','num_of_connections_200':'num_of_connections_200', 'num_of_connections_30':'num_of_connections_30', 'num_of_connections_50':'num_of_connections_50', 'num_of_connections_ADSL':'num_of_connections_ADSL',
                                                                                                                   'kvID_num':'kvID_num', 'ttl_num_of_connections':'ttl_num_of_connections'}).reset_index()

In [130]:
admin_aggs_fin = admin_aggs.merge(nomos_co_code_num, on="ADMIN_NAME")

In [131]:
admin_aggs_final = admin_aggs_fin.merge(geometry, on= "ADMIN_NAME")

In [132]:
admin_aggs_final.head(5)

,ADMIN_NAME,mean_Actual_Speed_100,mean_Actual_Speed_200,mean_Actual_Speed_30,mean_Actual_Speed_50,mean_Actual_Speed_ADSL,mean_disconnections_100,mean_disconnections_200,mean_disconnections_30,mean_disconnections_50,mean_disconnections_ADSL,num_of_connections_100,num_of_connections_200,num_of_connections_30,num_of_connections_50,num_of_connections_ADSL,VF MS,NGA availability,kvID_num,ttl_num_of_connections,VF base (retail services),CO_code_num,geometry
0,Achaia,80.586923,117.055714,28.624,45.131538,11.284211,17.230769,14.600000,11.200,22.407692,32.700000,3818.0,44.0,344.0,6468.0,11485.0,0.250500,0.376500,999,22159.0,27311.0,20,"MULTIPOLYGON (((21.38544 38.21083, 21.38414 38..."
1,Aitoloakarnania,63.580000,116.972500,30.755,43.114167,12.689583,63.383333,15.550000,54.825,38.200000,40.716667,2337.0,33.0,318.0,4025.0,6503.0,0.379167,0.275417,505,13216.0,15397.0,24,"MULTIPOLYGON (((21.51083 38.29036, 21.50917 38..."
2,Argolida,61.762500,27.520000,29.230,43.816000,13.512500,20.025000,233.000000,16.150,34.340000,33.700000,711.0,2.0,220.0,1125.0,1279.0,0.086667,0.575000,209,3337.0,3727.0,6,"MULTIPOLYGON (((23.14225 37.30043, 23.14081 37..."
3,Arkadia,62.673333,113.045000,30.800,48.710000,14.015000,14.300000,6.000000,14.900,12.600000,18.900000,571.0,10.0,66.0,983.0,1264.0,0.120000,0.536667,164,2894.0,3213.0,3,"MULTIPOLYGON (((22.84667 37.30125, 22.84581 37..."
4,Arta,68.801429,99.100000,NaN,45.115714,12.642500,58.200000,23.666667,NaN,40.028571,48.575000,470.0,7.0,0.0,802.0,2058.0,0.378750,0.501250,182,3337.0,4528.0,8,"MULTIPOLYGON (((20.92753 38.98539, 20.92664 38..."

In [133]:
admin_aggs_final["VF MS"] = admin_aggs_final["VF MS"].round(2)
admin_aggs_final["NGA availability"] = admin_aggs_final["NGA availability"].round(2)

In [134]:
admin_aggs_final["mean_Actual_Speed_100"] = admin_aggs_final["mean_Actual_Speed_100"].round(2)
admin_aggs_final["mean_Actual_Speed_200"] = admin_aggs_final["mean_Actual_Speed_200"].round(2)
admin_aggs_final["mean_Actual_Speed_30"] = admin_aggs_final["mean_Actual_Speed_30"].round(2)
admin_aggs_final["mean_Actual_Speed_50"] = admin_aggs_final["mean_Actual_Speed_50"].round(2)
admin_aggs_final["mean_Actual_Speed_ADSL"] = admin_aggs_final["mean_Actual_Speed_ADSL"].round(2)


admin_aggs_final["mean_disconnections_100"] = admin_aggs_final["mean_disconnections_100"].round(2)
admin_aggs_final["mean_disconnections_200"] = admin_aggs_final["mean_disconnections_200"].round(2)
admin_aggs_final["mean_disconnections_30"] = admin_aggs_final["mean_disconnections_30"].round(2)
admin_aggs_final["mean_disconnections_50"] = admin_aggs_final["mean_disconnections_50"].round(2)
admin_aggs_final["mean_disconnections_ADSL"] = admin_aggs_final["mean_disconnections_ADSL"].round(2)

In [135]:
admin_aggs_final.to_csv("nomos_layer.csv", index = False)

In [136]:
# from keplergl import KeplerGl
# map_1 = KeplerGl()
# display(map_1)

In [137]:
# !pip install ipywidget

In [138]:
# map_1.add_data(data=co_code_gr_area_data, name='nomoi')
# map_1

In [139]:
# map_1.save_to_html(file_name='C:/Users/mich... by Dimitris Michalopoulos, Vodafone')

# map_1.save_to_html(file_name='C:/Users/michalopoulosd/Desktop//dimoi.html')

# 4th layer

In [140]:
kvid_network_aggs_latlong

,CO_code,kvID,mean_Actual_Speed_100,mean_Actual_Speed_200,mean_Actual_Speed_30,mean_Actual_Speed_50,mean_Actual_Speed_ADSL,mean_disconnections_10,mean_disconnections_200,mean_disconnections_30,mean_disconnections_50,mean_disconnections_ADSL,num_of_connections_100,num_of_connections_200,num_of_connections_30,num_of_connections_50,num_of_connections_ADSL,longitude,latitude,num_of_connections_VDSL,icon
0,0,0,108.04,NO customers,NO customers,46.79,8.67,1.3,NO customers,NO customers,6.1,17.5,3,NO customers,NO customers,29,4,NaN,NaN,32.0,place
1,0,70,NO customers,NO customers,NO customers,37.48,NO customers,NO customers,NO customers,NO customers,11,NO customers,NO customers,NO customers,NO customers,1,NO customers,NaN,NaN,1.0,place
2,0,101,NO customers,NO customers,NO customers,26.84,14.57,NO customers,NO customers,NO customers,13.5,0,NO customers,NO customers,NO customers,4,1,NaN,NaN,4.0,place
3,0,103,7.95,NO customers,NO customers,8.19,28.4,20,NO customers,NO customers,1,8.3,1,NO customers,NO customers,1,3,NaN,NaN,2.0,place
4,0,105,NO customers,NO customers,NO customers,41.47,11.41,NO customers,NO customers,NO customers,27.8,6,NO customers,NO customers,NO customers,4,1,NaN,NaN,4.0,place
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32046,2269,105,56.06,NO customers,NO customers,50.19,NO customers,39.5,NO customers,NO customers,46,NO customers,2,NO customers,NO customers,2,NO customers,NaN,NaN,4.0,place
32047,9003,1,NO customers,NO customers,30.72,NO customers,NO customers,NO customers,NO customers,1,NO customers,NO customers,NO customers,NO customers,1,NO customers,NO customers,NaN,NaN,1.0,place
32048,9004,1,NO customers,NO customers,NO customers,56.32,NO customers,NO customers,NO customers,NO customers,0.3,NO customers,NO customers,NO customers,NO customers,6,NO customers,NaN,NaN,6.0,place
32049,9005,1,NO customers,NO customers,33.77,NO customers,NO customers,NO customers,NO customers,3,NO customers,NO customers,NO customers,NO customers,1,NO customers,NO customers,NaN,NaN,1.0,place
32050,9996,0,NO customers,NO customers,NO customers,NO customers,21.65,NO customers,NO customers,NO customers,NO customers,223,NO customers,NO customers,NO customers,NO customers,1,NaN,NaN,0.0,place

In [141]:
CO_code_network_coords_product

,longitude,latitude,Νομός Α/Κ,index,CO_code,mean_Actual_Speed_100,mean_Actual_Speed_200,mean_Actual_Speed_30,mean_Actual_Speed_50,mean_Actual_Speed_ADSL,mean_disconnections_100,mean_disconnections_200,mean_disconnections_30,mean_disconnections_50,mean_disconnections_ADSL,num_of_connections_100,num_of_connections_200,num_of_connections_30,num_of_connections_50,num_of_connections_ADSL,kvID_num,ttl_num_of_connections,CO code,OKSY C,NGA availability,VF base (retail services),VF MS,submitted 12m,created 12m,submitted 6m,created 6m,icon,num_of_connections_VDSL,speed_ttl_experience,geometry
0,22.853874,37.244403,ΑΡΚΑΔΙΑΣ,3,16,18.54,NaN,NaN,54.70,NaN,7.0,NaN,NaN,14.0,NaN,1.0,0.0,0.0,1.0,0.0,2,2.0,16,ACTIVE,0.47,2.0,0.00,2.0,2.0,0.0,0.0,home,2.0,73.24,POINT (22.85387 37.24440)
1,22.452459,36.959996,ΛΑΚΩΝΙΑΣ,5,27,39.29,NaN,NaN,49.25,NaN,171.0,NaN,NaN,316.5,NaN,1.0,0.0,0.0,2.0,0.0,1,3.0,27,ACTIVE,0.40,4.0,0.00,1.0,1.0,0.0,0.0,home,3.0,88.54,POINT (22.45246 36.96000)
2,22.078575,37.047754,ΜΕΣΣΗΝΙΑΣ,6,45,107.77,NaN,NaN,48.51,NaN,5.0,NaN,NaN,114.5,NaN,1.0,0.0,0.0,3.0,0.0,2,4.0,45,ACTIVE,0.37,5.0,0.01,10.0,12.0,5.0,6.0,home,4.0,156.28,POINT (22.07857 37.04775)
3,22.111926,37.034498,ΜΕΣΣΗΝΙΑΣ,7,47,90.75,133.71,27.13,51.45,11.46,16.0,77.0,26.7,9.6,31.2,1141.0,15.0,315.0,1562.0,1641.0,196,4674.0,47,ACTIVE,0.74,5275.0,0.21,834.0,988.0,435.0,506.0,home,3033.0,314.50,POINT (22.11193 37.03450)
4,21.941240,37.003638,ΜΕΣΣΗΝΙΑΣ,8,56,NaN,NaN,NaN,27.78,NaN,NaN,NaN,NaN,18.0,NaN,0.0,0.0,0.0,1.0,0.0,1,1.0,56,ACTIVE,0.28,1.0,0.00,NaN,NaN,NaN,NaN,home,1.0,27.78,POINT (21.94124 37.00364)
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
686,24.933898,37.436261,ΚΥΚΛΑΔΩΝ,829,2082,80.17,NaN,NaN,44.79,14.52,14.0,NaN,NaN,14.6,27.4,70.0,0.0,0.0,169.0,213.0,33,452.0,2082,ACTIVE,0.72,497.0,0.17,58.0,69.0,28.0,36.0,home,239.0,139.48,POINT (24.93390 37.43626)
687,22.521566,40.756624,ΠΕΛΛΗΣ,830,2083,NaN,NaN,NaN,NaN,13.45,NaN,NaN,NaN,NaN,6.5,0.0,0.0,0.0,0.0,86.0,6,86.0,2083,Inactive,0.00,288.0,0.47,NaN,NaN,NaN,NaN,home,0.0,13.45,POINT (22.52157 40.75662)
688,28.211207,36.380284,ΔΩΔΕΚΑΝΗΣΟΥ,831,2087,81.18,196.74,NaN,52.08,NaN,40.2,8.0,NaN,9.7,NaN,14.0,1.0,0.0,25.0,0.0,10,40.0,2087,ACTIVE,0.92,54.0,0.05,36.0,46.0,27.0,33.0,home,40.0,330.00,POINT (28.21121 36.38028)
689,21.485059,38.608638,ΑΙΤΩΛΟΑΚΑΡΝΑΝΙΑΣ,832,2091,71.59,52.34,NaN,49.95,15.88,25.5,14.5,NaN,18.1,58.9,51.0,3.0,0.0,113.0,90.0,13,257.0,2091,ACTIVE,0.93,277.0,0.39,30.0,36.0,14.0,17.0,home,167.0,189.76,POINT (21.48506 38.60864)
690,25.037444,35.396333,ΛΥΓΑΡΙΑ,827,2079,NaN,NaN,NaN,55.00,NaN,NaN,NaN,NaN,4.0,NaN,0.0,0.0,0.0,1.0,0.0,1,1.0,2079,ACTIVE,0.42,8.0,0.03,3.0,3.0,2.0,2.0,home,1.0,55.00,POINT (25.03744 35.39633)

In [142]:
connectivity = CO_code_network_coords_product[["CO code", "longitude", "latitude"]].merge(kvid_network_aggs_latlong[["CO_code", 'kvID', 'longitude', 'latitude']], left_on='CO code', right_on='CO_code')

In [143]:
connectivity

,CO code,longitude_x,latitude_x,CO_code,kvID,longitude_y,latitude_y
0,16,22.853874,37.244403,16,102,22.855167,37.248389
1,16,22.853874,37.244403,16,103,22.861222,37.246222
2,27,22.452459,36.959996,27,201,22.441472,36.979083
3,45,22.078575,37.047754,45,45,NaN,NaN
4,45,22.078575,37.047754,45,203,22.066806,37.057722
...,...,...,...,...,...,...,...
31468,2091,21.485059,38.608638,2091,211,21.481528,38.603444
31469,2091,21.485059,38.608638,2091,213,21.478722,38.602806
31470,2091,21.485059,38.608638,2091,323,NaN,NaN
31471,2091,21.485059,38.608638,2091,426,NaN,NaN
31472,2079,25.037444,35.396333,2079,103,25.029778,35.396833

In [144]:
connectivity.to_csv("connectivity.csv", index = False)

In [145]:
connectivity[(connectivity["kvID"] == 203) & (connectivity["CO code"] == 2023)]

Empty DataFrame
Columns: [CO code, longitude_x, latitude_x, CO_code, kvID, longitude_y, latitude_y]
Index: []

In [146]:
kvid_network_aggs_latlong[kvid_network_aggs_latlong["CO_code"] == 2023]

,CO_code,kvID,mean_Actual_Speed_100,mean_Actual_Speed_200,mean_Actual_Speed_30,mean_Actual_Speed_50,mean_Actual_Speed_ADSL,mean_disconnections_10,mean_disconnections_200,mean_disconnections_30,mean_disconnections_50,mean_disconnections_ADSL,num_of_connections_100,num_of_connections_200,num_of_connections_30,num_of_connections_50,num_of_connections_ADSL,longitude,latitude,num_of_connections_VDSL,icon
31111,2023,104,46.43,NO customers,NO customers,55,NO customers,4,NO customers,NO customers,5,NO customers,1,NO customers,NO customers,1,NO customers,22.852972,36.727250,2.0,place
31112,2023,105,NO customers,NO customers,NO customers,55,NO customers,NO customers,NO customers,NO customers,4,NO customers,NO customers,NO customers,NO customers,1,NO customers,22.851500,36.728500,1.0,place
31113,2023,106,75.33,NO customers,NO customers,54.25,NO customers,32,NO customers,NO customers,110,NO customers,1,NO customers,NO customers,2,NO customers,22.854306,36.729444,3.0,place
31114,2023,107,61.64,58.65,NO customers,32.96,NO customers,15,3,NO customers,140.7,NO customers,2,1,NO customers,3,NO customers,22.854472,36.730806,6.0,place
31115,2023,203,NO customers,NO customers,NO customers,50.62,NO customers,NO customers,NO customers,NO customers,5,NO customers,NO customers,NO customers,NO customers,9,NO customers,22.901528,36.737028,9.0,place
31116,2023,405,NO customers,NO customers,NO customers,53.74,NO customers,NO customers,NO customers,NO customers,2,NO customers,NO customers,NO customers,NO customers,1,NO customers,22.838778,36.689833,1.0,place
31117,2023,406,NO customers,NO customers,NO customers,47.47,NO customers,NO customers,NO customers,NO customers,6,NO customers,NO customers,NO customers,NO customers,3,NO customers,22.840389,36.690778,3.0,place

In [147]:
CO_code_network_coords_product[CO_code_network_coords_product["CO code"] == 2023]

Empty DataFrame
Columns: [longitude, latitude, Νομός Α/Κ, index, CO_code, mean_Actual_Speed_100, mean_Actual_Speed_200, mean_Actual_Speed_30, mean_Actual_Speed_50, mean_Actual_Speed_ADSL, mean_disconnections_100, mean_disconnections_200, mean_disconnections_30, mean_disconnections_50, mean_disconnections_ADSL, num_of_connections_100, num_of_connections_200, num_of_connections_30, num_of_connections_50, num_of_connections_ADSL, kvID_num, ttl_num_of_connections, CO code, OKSY C, NGA availability, VF base (retail services), VF MS, submitted 12m, created 12m, submitted 6m, created 6m, icon, num_of_connections_VDSL, speed_ttl_experience, geometry]
Index: []